/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './features/**/*.{js,jsx}',
    './providers/**/*.{js,jsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'ivory-base': '#FCFAF2',
        'matte-black': '#121212',
        'champagne-gold': '#E2C9A1',
        'warm-white': '#FDFDFD',
        'soft-beige': '#F3E8E7',
        'surface': '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#4d4635',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        'outline': '#7f7663',
        'outline-variant': '#d0c5af',
        'surface-tint': '#735c00',
        'primary': '#735c00',
        'on-primary': '#ffffff',
        'primary-container': '#d4af37',
        'on-primary-container': '#554300',
        'inverse-primary': '#e9c349',
        'secondary': '#5d5f5b',
        'on-secondary': '#ffffff',
        'secondary-container': '#e0e0db',
        'on-secondary-container': '#62635f',
        'tertiary': '#6a5d43',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c2b193',
        'on-tertiary-container': '#4f442c',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#fcf9f8',
        'on-background': '#1c1b1b',
      },
      fontFamily: {
        bodoni: ['"Bodoni Moda"', 'serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['80px', { lineHeight: '96px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-xl-mobile': ['48px', { lineHeight: '56px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '56px', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '32px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
      },
      spacing: {
        'margin-desktop': '80px',
        'margin-mobile': '24px',
        'unit': '8px',
        'gutter': '32px',
        'container-max': '1440px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      borderRadius: {
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '9999px',
      },
      transitionTimingFunction: {
        'luxury': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'slow-ease': 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
      },
      animation: {
        'fade-in': 'fadeIn 1.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-up': 'slideUp 1s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'draw-line': 'drawLine 2s ease forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(40px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        drawLine: {
          '0%': { strokeDashoffset: '1000' },
          '100%': { strokeDashoffset: '0' },
        },
      },
      backdropBlur: {
        'xs': '2px',
      },
      boxShadow: {
        'product': '0 20px 40px rgba(0,0,0,0.04)',
        'glass': '0 8px 32px rgba(115, 92, 0, 0.08)',
        'deep': '0 40px 80px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
};
