"""
Seed Script — Éclat Platform
Inserts sample products into PostgreSQL and syncs to Pinecone.
Run: python -m app.products.seed_products
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.database.connection import SessionLocal, create_tables
from app.products.product_service import create_product
from app.chatbot.pinecone_service import bulk_upsert_products

PRODUCTS = [
    {
        "slug": "diamond-solitaire-necklace",
        "name": "Diamond Solitaire Pendant",
        "description": "A breathtaking 0.5ct round brilliant diamond suspended on an 18K gold chain. Timeless. Unapologetically beautiful.",
        "shortDescription": "0.5ct round brilliant diamond on 18K gold chain.",
        "price": 145000,
        "stock": 8,
        "images": [
            "https://ik.imagekit.io/eclat/diamond-solitaire-1.jpg",
            "https://ik.imagekit.io/eclat/diamond-solitaire-2.jpg",
        ],
        "category": "necklace",
        "collection": "Eternal",
        "materials": ["gold", "diamond"],
        "gemstones": ["diamond"],
        "gender": ["female", "unisex"],
        "occasions": ["wedding", "anniversary", "gifting"],
        "styleTags": ["timeless", "elegant", "luxury", "bridal"],
        "tags": ["diamond", "necklace", "gold", "bridal"],
        "wearType": "neck",
        "embeddingText": "Elegant 18K gold diamond solitaire necklace designed for wedding and anniversary occasions with timeless luxury aesthetics and bridal elegance for women",
        "relatedProducts": [],
        "completeLook": [],
        "featured": True,
        "isNew": False,
        "isBestseller": True,
        "rating": 4.9,
        "reviewCount": 127,
    },
    {
        "slug": "minimal-gold-link-bracelet",
        "name": "Minimal Gold Link Bracelet",
        "description": "Delicate 18K yellow gold links crafted for everyday luxury. A whisper of gold around the wrist.",
        "shortDescription": "18K yellow gold everyday bracelet.",
        "price": 38500,
        "stock": 14,
        "images": ["https://ik.imagekit.io/eclat/gold-bracelet-1.jpg"],
        "category": "bracelet",
        "collection": "Quotidien",
        "materials": ["gold"],
        "gemstones": [],
        "gender": ["female", "unisex"],
        "occasions": ["daily", "gifting", "anniversary"],
        "styleTags": ["minimal", "contemporary", "everyday"],
        "tags": ["gold", "bracelet", "minimal"],
        "wearType": "hands",
        "embeddingText": "Minimal 18K yellow gold link bracelet for everyday wear, contemporary design, lightweight, perfect gifting piece for women",
        "relatedProducts": [],
        "completeLook": [],
        "featured": False,
        "isNew": True,
        "isBestseller": False,
        "rating": 4.7,
        "reviewCount": 89,
    },
    {
        "slug": "ruby-drop-earrings",
        "name": "Ruby Pavé Drop Earrings",
        "description": "Deep Burmese rubies set in a cascading pavé drop. Designed for the woman who enters a room and changes it.",
        "shortDescription": "Burmese rubies in 18K gold pavé drop setting.",
        "price": 89000,
        "stock": 5,
        "images": ["https://ik.imagekit.io/eclat/ruby-earrings-1.jpg"],
        "category": "earrings",
        "collection": "Lumière Rouge",
        "materials": ["gold", "ruby"],
        "gemstones": ["ruby"],
        "gender": ["female"],
        "occasions": ["wedding", "party", "festive"],
        "styleTags": ["bold", "dramatic", "luxury", "statement"],
        "tags": ["ruby", "earrings", "statement"],
        "wearType": "ears",
        "embeddingText": "Bold ruby pavé drop earrings in 18K gold for weddings and special occasions, dramatic statement jewellery for women who command attention",
        "relatedProducts": [],
        "completeLook": [],
        "featured": True,
        "isNew": False,
        "isBestseller": False,
        "rating": 4.8,
        "reviewCount": 43,
    },
    {
        "slug": "emerald-cocktail-ring",
        "name": "Emerald Cocktail Ring",
        "description": "A 3ct Colombian emerald, cathedral-set in 18K white gold with diamond shoulders. Bold. Intentional. Unforgettable.",
        "shortDescription": "3ct Colombian emerald in 18K white gold with diamond shoulders.",
        "price": 210000,
        "stock": 3,
        "images": ["https://ik.imagekit.io/eclat/emerald-ring-1.jpg"],
        "category": "ring",
        "collection": "Vivid",
        "materials": ["white gold", "diamond", "emerald"],
        "gemstones": ["emerald", "diamond"],
        "gender": ["female"],
        "occasions": ["party", "anniversary", "gifting"],
        "styleTags": ["bold", "luxury", "statement", "cocktail"],
        "tags": ["emerald", "ring", "statement", "diamond"],
        "wearType": "rings",
        "embeddingText": "Bold emerald cocktail ring 3ct Colombian emerald 18K white gold diamond shoulders luxury statement jewellery for women anniversary party",
        "relatedProducts": [],
        "completeLook": [],
        "featured": True,
        "isNew": False,
        "isBestseller": True,
        "rating": 5.0,
        "reviewCount": 18,
    },
    {
        "slug": "platinum-solitaire-band",
        "name": "Platinum Solitaire Band",
        "description": "A full-circle pavé of round brilliants set in platinum. Every angle, a new constellation.",
        "shortDescription": "Full pavé diamond eternity band in platinum.",
        "price": 175000,
        "stock": 6,
        "images": ["https://ik.imagekit.io/eclat/platinum-band-1.jpg"],
        "category": "ring",
        "collection": "Eternal",
        "materials": ["platinum", "diamond"],
        "gemstones": ["diamond"],
        "gender": ["female", "unisex"],
        "occasions": ["wedding", "anniversary"],
        "styleTags": ["timeless", "elegant", "bridal", "minimal"],
        "tags": ["platinum", "ring", "diamond", "eternity"],
        "wearType": "rings",
        "embeddingText": "Platinum pavé diamond eternity band ring for wedding bridal engagement timeless elegant minimal design for women",
        "relatedProducts": [],
        "completeLook": [],
        "featured": False,
        "isNew": False,
        "isBestseller": True,
        "rating": 4.9,
        "reviewCount": 211,
    },
    {
        "slug": "rose-gold-layered-necklace",
        "name": "Rose Gold Layered Necklace",
        "description": "Three delicate chains of 18K rose gold, lengths curated to fall in perfect asymmetry. The everyday luxe.",
        "shortDescription": "Three-tier 18K rose gold layered chain necklace.",
        "price": 52000,
        "stock": 9,
        "images": ["https://ik.imagekit.io/eclat/rose-gold-necklace-1.jpg"],
        "category": "necklace",
        "collection": "Quotidien",
        "materials": ["rose gold"],
        "gemstones": [],
        "gender": ["female"],
        "occasions": ["daily", "gifting", "anniversary"],
        "styleTags": ["romantic", "feminine", "layered", "contemporary"],
        "tags": ["rose gold", "necklace", "layered", "daily"],
        "wearType": "neck",
        "embeddingText": "Romantic rose gold layered necklace three chains feminine contemporary everyday luxury wear for women gifting anniversary",
        "relatedProducts": [],
        "completeLook": [],
        "featured": False,
        "isNew": True,
        "isBestseller": False,
        "rating": 4.6,
        "reviewCount": 64,
    },
    {
        "slug": "silver-hoop-earrings-minimal",
        "name": "Sterling Silver Architectural Hoops",
        "description": "Oversized, polished, architectural. These hoops don't just hang — they declare.",
        "shortDescription": "Oversized polished sterling silver hoop earrings.",
        "price": 12500,
        "stock": 22,
        "images": ["https://ik.imagekit.io/eclat/silver-hoops-1.jpg"],
        "category": "earrings",
        "collection": "Structure",
        "materials": ["silver"],
        "gemstones": [],
        "gender": ["female", "unisex"],
        "occasions": ["daily", "party"],
        "styleTags": ["minimal", "architectural", "editorial", "modern"],
        "tags": ["silver", "earrings", "hoop", "minimal"],
        "wearType": "ears",
        "embeddingText": "Minimal architectural oversized sterling silver hoop earrings editorial modern contemporary daily wear statement jewellery",
        "relatedProducts": [],
        "completeLook": [],
        "featured": False,
        "isNew": True,
        "isBestseller": False,
        "rating": 4.5,
        "reviewCount": 156,
    },
    {
        "slug": "mens-gold-chain-bold",
        "name": "Men's Cuban Link Chain",
        "description": "Substantial 18K yellow gold Cuban links. Heavyweight presence. Worn alone or over a shirt — it always commands.",
        "shortDescription": "Heavy 18K yellow gold Cuban link chain for men.",
        "price": 285000,
        "stock": 4,
        "images": ["https://ik.imagekit.io/eclat/mens-chain-1.jpg"],
        "category": "necklace",
        "collection": "Prestige",
        "materials": ["gold"],
        "gemstones": [],
        "gender": ["male", "unisex"],
        "occasions": ["daily", "party"],
        "styleTags": ["bold", "luxury", "statement", "heavyweight"],
        "tags": ["gold", "chain", "men", "bold"],
        "wearType": "neck",
        "embeddingText": "Bold heavyweight 18K gold Cuban link chain for men luxury statement necklace strong masculine daily wear party",
        "relatedProducts": [],
        "completeLook": [],
        "featured": True,
        "isNew": False,
        "isBestseller": False,
        "rating": 4.8,
        "reviewCount": 37,
    },
    {
        "slug": "sapphire-tennis-bracelet",
        "name": "Blue Sapphire Tennis Bracelet",
        "description": "Ceylon sapphires in a seamless prong-set line of 18K white gold. The tennis bracelet, reimagined with colour.",
        "shortDescription": "Ceylon sapphire tennis bracelet in 18K white gold.",
        "price": 132000,
        "stock": 7,
        "images": ["https://ik.imagekit.io/eclat/sapphire-bracelet-1.jpg"],
        "category": "bracelet",
        "collection": "Vivid",
        "materials": ["white gold", "sapphire"],
        "gemstones": ["sapphire"],
        "gender": ["female"],
        "occasions": ["wedding", "anniversary", "party"],
        "styleTags": ["elegant", "luxury", "timeless", "bridal"],
        "tags": ["sapphire", "bracelet", "white gold", "tennis"],
        "wearType": "hands",
        "embeddingText": "Blue sapphire tennis bracelet 18K white gold elegant timeless luxury bridal wedding anniversary women statement",
        "relatedProducts": [],
        "completeLook": [],
        "featured": False,
        "isNew": False,
        "isBestseller": False,
        "rating": 4.9,
        "reviewCount": 29,
    },
    {
        "slug": "diamond-stud-earrings-classic",
        "name": "Classic Diamond Stud Earrings",
        "description": "0.5ct each. Round brilliants. Four-claw platinum setting. The earrings every woman deserves to own.",
        "shortDescription": "0.5ct diamond studs in four-claw platinum setting.",
        "price": 95000,
        "stock": 12,
        "images": ["https://ik.imagekit.io/eclat/diamond-studs-1.jpg"],
        "category": "earrings",
        "collection": "Eternal",
        "materials": ["platinum", "diamond"],
        "gemstones": ["diamond"],
        "gender": ["female", "unisex"],
        "occasions": ["daily", "wedding", "gifting", "anniversary"],
        "styleTags": ["classic", "timeless", "elegant", "minimal"],
        "tags": ["diamond", "studs", "earrings", "classic"],
        "wearType": "ears",
        "embeddingText": "Classic diamond stud earrings 0.5ct round brilliant platinum four claw setting timeless elegant daily wear gifting women anniversary wedding",
        "relatedProducts": [],
        "completeLook": [],
        "featured": True,
        "isNew": False,
        "isBestseller": True,
        "rating": 4.9,
        "reviewCount": 342,
    },
     {
        "slug": "oxidized-lotus-pendant-necklace",
        "name": "Oxidized Lotus Pendant Necklace",
        "description": "Elegant oxidized lotus pendant necklace with spiritual design. Perfect for daily wear.",
        "shortDescription": "Oxidized lotus pendant",
        "price": 579.0, "originalPrice": 849.0, "discount": 31.0, "stock": 14,
        "rating": 4.7, "reviewCount": 68,
        "images": ["https://ik.imagekit.io/lrpk6giraj/26529085300793173.jpg"],
        "category": "Pendant", "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"], "gemstones": [], "dimensions": "18 inch chain",
        "gender": ["Women"], "occasions": ["Daily Wear", "Festive", "Religious"],
        "styleTags": ["Spiritual", "Ethnic", "Elegant"],
        "tags": ["Pendant", "Lotus", "Oxidized", "Spiritual"], "wearType": "Neck",
        "embeddingText": "Elegant oxidized lotus pendant necklace spiritual ethnic design for daily wear festive religious occasions.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "oxidized-silver-anklet-pair",
        "name": "Oxidized Silver Anklet Pair",
        "description": "Beautiful pair of oxidized silver anklets with ghungroo bells. Traditional ethnic style.",
        "shortDescription": "Oxidized silver anklet pair",
        "price": 649.0, "originalPrice": 949.0, "discount": 31.0, "stock": 16,
        "rating": 4.6, "reviewCount": 72,
        "images": ["https://ik.imagekit.io/lrpk6giraj/292030357099537261.jpg"],
        "category": "Bracelet", "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"], "gemstones": [], "dimensions": "10 inch",
        "gender": ["Women"], "occasions": ["Festive", "Wedding", "Daily Wear"],
        "styleTags": ["Traditional", "Ethnic", "Classic"],
        "tags": ["Anklet", "Pair", "Silver", "Oxidized", "Ghungroo"], "wearType": "Ankle",
        "embeddingText": "Beautiful pair oxidized silver anklets ghungroo bells traditional ethnic style for festive wedding daily wear.",
        "relatedProducts": [], "completeLook": [], "featured": False, "isNew": True, "isBestseller": True,
    },
    {
        "slug": "oxidized-coin-necklace-ethnic",
        "name": "Oxidized Coin Necklace Ethnic",
        "description": "Traditional oxidized coin necklace with ethnic design. Vintage look for festive occasions.",
        "shortDescription": "Oxidized coin necklace",
        "price": 849.0, "originalPrice": 1199.0, "discount": 29.0, "stock": 10,
        "rating": 4.8, "reviewCount": 82,
        "images": ["https://ik.imagekit.io/lrpk6giraj/703265298107893485.jpg"],
        "category": "Necklace", "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"], "gemstones": [], "dimensions": "20 inch",
        "gender": ["Women"], "occasions": ["Festive", "Wedding", "Party"],
        "styleTags": ["Vintage", "Ethnic", "Traditional"],
        "tags": ["Necklace", "Coin", "Oxidized", "Vintage"], "wearType": "Neck",
        "embeddingText": "Traditional oxidized coin necklace ethnic vintage look for festive wedding party occasions.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": False, "isBestseller": True,
    },
    {
        "slug": "oxidized-mirror-work-earrings",
        "name": "Oxidized Mirror Work Earrings",
        "description": "Stunning oxidized earrings with mirror work design. Rajasthani ethnic style.",
        "shortDescription": "Oxidized mirror work earrings",
        "price": 579.0, "originalPrice": 849.0, "discount": 31.0, "stock": 12,
        "rating": 4.7, "reviewCount": 88,
        "images": ["https://ik.imagekit.io/lrpk6giraj/236790892900808893.jpg"],
        "category": "Earrings", "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"], "gemstones": [], "dimensions": "5 cm",
        "gender": ["Women"], "occasions": ["Festive", "Wedding", "Party"],
        "styleTags": ["Rajasthani", "Ethnic", "Boho", "Mirror Work"],
        "tags": ["Earrings", "Mirror Work", "Oxidized", "Rajasthani"], "wearType": "Ear",
        "embeddingText": "Stunning oxidized mirror work earrings Rajasthani ethnic boho style for festive wedding party.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "oxidized-silver-maang-tikka",
        "name": "Oxidized Silver Maang Tikka",
        "description": "Traditional oxidized silver maang tikka with ethnic design. Perfect for bridal occasions.",
        "shortDescription": "Oxidized silver maang tikka",
        "price": 699.0, "originalPrice": 999.0, "discount": 30.0, "stock": 10,
        "rating": 4.8, "reviewCount": 65,
        "images": ["https://ik.imagekit.io/lrpk6giraj/485403666111634906.jpg"],
        "category": "Pendant", "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"], "gemstones": [], "dimensions": "Adjustable",
        "gender": ["Women"], "occasions": ["Wedding", "Festive", "Engagement"],
        "styleTags": ["Bridal", "Traditional", "Ethnic", "Royal"],
        "tags": ["Maang Tikka", "Silver", "Oxidized", "Bridal"], "wearType": "Hair",
        "embeddingText": "Traditional oxidized silver maang tikka ethnic bridal design for wedding festive engagement occasions.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": True,
    },
    {
        "slug": "oxidized-elephant-pendant-necklace",
        "name": "Oxidized Elephant Pendant Necklace",
        "description": "Lucky oxidized elephant pendant necklace. Traditional ethnic design with good luck charm.",
        "shortDescription": "Oxidized elephant pendant",
        "price": 549.0, "originalPrice": 799.0, "discount": 31.0, "stock": 18,
        "rating": 4.6, "reviewCount": 75,
        "images": ["https://ik.imagekit.io/lrpk6giraj/332562753743330773.jpg"],
        "category": "Pendant", "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"], "gemstones": [], "dimensions": "18 inch chain",
        "gender": ["Women"], "occasions": ["Daily Wear", "Festive", "Religious"],
        "styleTags": ["Lucky", "Ethnic", "Traditional", "Spiritual"],
        "tags": ["Pendant", "Elephant", "Oxidized", "Lucky"], "wearType": "Neck",
        "embeddingText": "Lucky oxidized elephant pendant necklace traditional ethnic spiritual for daily wear festive religious.",
        "relatedProducts": [], "completeLook": [], "featured": False, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "oxidized-vintage-ring-set",
        "name": "Oxidized Vintage Ring Set",
        "description": "Set of 3 oxidized vintage rings with ethnic design. Mix and match for festive look.",
        "shortDescription": "Oxidized vintage ring set of 3",
        "price": 699.0, "originalPrice": 999.0, "discount": 30.0, "stock": 15,
        "rating": 4.5, "reviewCount": 92,
        "images": ["https://ik.imagekit.io/lrpk6giraj/209487820161858162.jpg"],
        "category": "Ring", "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"], "gemstones": [], "dimensions": "Size 16-18",
        "gender": ["Women"], "occasions": ["Festive", "Casual", "Daily Wear"],
        "styleTags": ["Vintage", "Ethnic", "Set", "Mix Match"],
        "tags": ["Ring", "Set", "Vintage", "Oxidized"], "wearType": "Finger",
        "embeddingText": "Set of 3 oxidized vintage rings ethnic design mix match festive casual daily wear women.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "oxidized-tree-of-life-pendant",
        "name": "Oxidized Tree of Life Pendant",
        "description": "Beautiful oxidized tree of life pendant necklace. Symbolic ethnic jewelry.",
        "shortDescription": "Oxidized tree of life pendant",
        "price": 599.0, "originalPrice": 899.0, "discount": 33.0, "stock": 14,
        "rating": 4.7, "reviewCount": 58,
        "images": ["https://ik.imagekit.io/lrpk6giraj/128071183149611312.jpg"],
        "category": "Pendant", "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"], "gemstones": [], "dimensions": "18 inch chain",
        "gender": ["Women"], "occasions": ["Daily Wear", "Casual", "Gifting"],
        "styleTags": ["Symbolic", "Nature", "Ethnic", "Spiritual"],
        "tags": ["Pendant", "Tree of Life", "Oxidized", "Symbolic"], "wearType": "Neck",
        "embeddingText": "Beautiful oxidized tree of life pendant symbolic ethnic spiritual jewelry for daily wear casual gifting.",
        "relatedProducts": [], "completeLook": [], "featured": False, "isNew": True, "isBestseller": True,
    },
    {
        "slug": "oxidized-statement-bangle-wide",
        "name": "Oxidized Statement Wide Bangle",
        "description": "Bold oxidized wide statement bangle with intricate ethnic pattern. Eye-catching piece.",
        "shortDescription": "Oxidized wide statement bangle",
        "price": 849.0, "originalPrice": 1199.0, "discount": 29.0, "stock": 10,
        "rating": 4.8, "reviewCount": 55,
        "images": ["https://ik.imagekit.io/lrpk6giraj/A%20set%20of%20bangles%20consisting%20of%20two%20pieces_.jpg"],
        "category": "Bangle", "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"], "gemstones": [], "dimensions": "2.6 size",
        "gender": ["Women"], "occasions": ["Wedding", "Festive", "Party"],
        "styleTags": ["Bold", "Statement", "Ethnic", "Royal"],
        "tags": ["Bangle", "Wide", "Statement", "Oxidized"], "wearType": "Wrist",
        "embeddingText": "Bold oxidized wide statement bangle intricate ethnic pattern eye-catching for wedding festive party.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": False, "isBestseller": True,
    },
    {
        "slug": "oxidized-boho-layered-necklace",
        "name": "Oxidized Boho Layered Necklace",
        "description": "Trendy oxidized boho layered necklace with ethnic charms. Perfect for casual and festive.",
        "shortDescription": "Oxidized boho layered necklace",
        "price": 899.0, "originalPrice": 1299.0, "discount": 30.0, "stock": 12,
        "rating": 4.7, "reviewCount": 78,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Oxidised%20set%20comes%20with%20openable%20bangles%20%C2%A0necklace_.jpg"],
        "category": "Necklace", "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"], "gemstones": [], "dimensions": "16-20 inch",
        "gender": ["Women"], "occasions": ["Casual", "Festive", "Party"],
        "styleTags": ["Boho", "Layered", "Trendy", "Ethnic"],
        "tags": ["Necklace", "Boho", "Layered", "Oxidized"], "wearType": "Neck",
        "embeddingText": "Trendy oxidized boho layered necklace ethnic charms casual festive party women.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
 
    # ═══════════════════════════════════════
    # 40 TINTED / ANTI-TARNISH PRODUCTS
    # ═══════════════════════════════════════
 
    {
        "slug": "tinted-blue-stone-ring",
        "name": "Tinted Blue Stone Ring",
        "description": "Elegant ring with tinted blue stone setting. Anti-tarnish silver base.",
        "shortDescription": "Tinted blue stone ring",
        "price": 599.0, "originalPrice": 899.0, "discount": 33.0, "stock": 25,
        "rating": 4.5, "reviewCount": 80,
        "images": ["https://ik.imagekit.io/lrpk6giraj/316%20Anti%20tarnished%20rings%E2%9C%A8___.jpg"],
        "category": "Ring", "collection": "Tinted Collection",
        "materials": ["Silver", "Blue Stone", "Anti-Tarnish"], "gemstones": ["Blue Topaz"],
        "dimensions": "Size 17", "gender": ["Women"],
        "occasions": ["Casual", "Office", "Party"],
        "styleTags": ["Trendy", "Colorful", "Minimal"],
        "tags": ["Ring", "Tinted", "Blue", "Stone"], "wearType": "Finger",
        "embeddingText": "Elegant tinted blue stone ring anti-tarnish silver trendy colorful for casual office party women.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-green-stone-earrings",
        "name": "Tinted Green Stone Earrings",
        "description": "Stylish earrings with tinted green stone. Anti-tarnish gold plated.",
        "shortDescription": "Tinted green stone earrings",
        "price": 549.0, "originalPrice": 799.0, "discount": 31.0, "stock": 22,
        "rating": 4.6, "reviewCount": 90,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Classy%20hoop%20earrings%20_%20Anti%20tarnished%20jewellery_.jpg"],
        "category": "Earrings", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Green Stone", "Anti-Tarnish"], "gemstones": ["Green Onyx"],
        "dimensions": "2 cm", "gender": ["Women"],
        "occasions": ["Casual", "Office", "Festive"],
        "styleTags": ["Trendy", "Colorful", "Elegant"],
        "tags": ["Earrings", "Tinted", "Green", "Stone"], "wearType": "Ear",
        "embeddingText": "Stylish tinted green stone earrings anti-tarnish gold plated colorful trendy for casual office festive.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": True,
    },
    {
        "slug": "tinted-pink-rose-quartz-necklace",
        "name": "Tinted Pink Rose Quartz Necklace",
        "description": "Beautiful necklace with tinted pink rose quartz pendant. Romantic anti-tarnish.",
        "shortDescription": "Tinted pink quartz necklace",
        "price": 799.0, "originalPrice": 1199.0, "discount": 33.0, "stock": 14,
        "rating": 4.7, "reviewCount": 105,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Pinteresty%20heart%20necklace%20%E2%99%A5%EF%B8%8F%20Anti%20tarnish_.jpg"],
        "category": "Necklace", "collection": "Tinted Collection",
        "materials": ["Silver", "Rose Quartz", "Anti-Tarnish"], "gemstones": ["Rose Quartz"],
        "dimensions": "18 inch", "gender": ["Women"],
        "occasions": ["Party", "Casual", "Valentine"],
        "styleTags": ["Romantic", "Colorful", "Trendy", "Pink"],
        "tags": ["Necklace", "Tinted", "Pink", "Rose Quartz"], "wearType": "Neck",
        "embeddingText": "Beautiful tinted pink rose quartz necklace romantic anti-tarnish colorful for party casual valentine women.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-red-stone-bangle",
        "name": "Tinted Red Stone Bangle",
        "description": "Stunning tinted red stone bangle with gold plating. Anti-tarnish festive piece.",
        "shortDescription": "Tinted red stone bangle",
        "price": 699.0, "originalPrice": 999.0, "discount": 30.0, "stock": 16,
        "rating": 4.6, "reviewCount": 72,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Floral%20Bangle%20Open-Type%20(Anti%20Tarnish)%20-%20Available_.jpg"],
        "category": "Bangle", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Red Stone", "Anti-Tarnish"], "gemstones": ["Ruby"],
        "dimensions": "2.6 size", "gender": ["Women"],
        "occasions": ["Festive", "Wedding", "Party"],
        "styleTags": ["Bold", "Colorful", "Festive", "Statement"],
        "tags": ["Bangle", "Tinted", "Red", "Stone"], "wearType": "Wrist",
        "embeddingText": "Stunning tinted red stone bangle gold plating anti-tarnish bold colorful for festive wedding party.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": False, "isBestseller": True,
    },
    {
        "slug": "tinted-purple-amethyst-ring",
        "name": "Tinted Purple Amethyst Ring",
        "description": "Elegant tinted purple amethyst ring. Anti-tarnish silver with vibrant stone.",
        "shortDescription": "Tinted purple amethyst ring",
        "price": 649.0, "originalPrice": 949.0, "discount": 31.0, "stock": 18,
        "rating": 4.7, "reviewCount": 85,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Why%20You_ll%20Love%20It_%20%E2%9C%94%EF%B8%8F%20Anti-Tarnish%20Coating%20__.jpg"],
        "category": "Ring", "collection": "Tinted Collection",
        "materials": ["Silver", "Amethyst", "Anti-Tarnish"], "gemstones": ["Amethyst"],
        "dimensions": "Size 17", "gender": ["Women"],
        "occasions": ["Casual", "Party", "Office"],
        "styleTags": ["Elegant", "Colorful", "Purple", "Trendy"],
        "tags": ["Ring", "Tinted", "Purple", "Amethyst"], "wearType": "Finger",
        "embeddingText": "Elegant tinted purple amethyst ring anti-tarnish silver vibrant colorful for casual party office women.",
        "relatedProducts": [], "completeLook": [], "featured": False, "isNew": True, "isBestseller": True,
    },
    {
        "slug": "tinted-multicolor-stone-earrings",
        "name": "Tinted Multicolor Stone Earrings",
        "description": "Vibrant tinted multicolor stone earrings. Anti-tarnish rainbow style.",
        "shortDescription": "Tinted multicolor stone earrings",
        "price": 599.0, "originalPrice": 899.0, "discount": 33.0, "stock": 20,
        "rating": 4.6, "reviewCount": 95,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Jewelry%20set%20you%20absolutely%20NEED%20Earrings%20X_.jpg"],
        "category": "Earrings", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Multicolor Stones", "Anti-Tarnish"], "gemstones": ["Mixed Stones"],
        "dimensions": "2.5 cm", "gender": ["Women"],
        "occasions": ["Festive", "Party", "Casual"],
        "styleTags": ["Vibrant", "Colorful", "Rainbow", "Trendy"],
        "tags": ["Earrings", "Tinted", "Multicolor", "Stone"], "wearType": "Ear",
        "embeddingText": "Vibrant tinted multicolor stone earrings anti-tarnish rainbow colorful for festive party casual women.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-turquoise-pendant-necklace",
        "name": "Tinted Turquoise Pendant Necklace",
        "description": "Beautiful tinted turquoise pendant necklace. Bohemian anti-tarnish style.",
        "shortDescription": "Tinted turquoise pendant",
        "price": 699.0, "originalPrice": 999.0, "discount": 30.0, "stock": 15,
        "rating": 4.7, "reviewCount": 78,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Dew%20Drop%20Heart%20Necklace_%20%20%E2%82%B9499_-%20(+shipping)%20%20DM_.jpg"],
        "category": "Necklace", "collection": "Tinted Collection",
        "materials": ["Silver", "Turquoise", "Anti-Tarnish"], "gemstones": ["Turquoise"],
        "dimensions": "18 inch", "gender": ["Women"],
        "occasions": ["Casual", "Festive", "Party"],
        "styleTags": ["Boho", "Colorful", "Turquoise", "Trendy"],
        "tags": ["Necklace", "Tinted", "Turquoise", "Boho"], "wearType": "Neck",
        "embeddingText": "Beautiful tinted turquoise pendant necklace bohemian anti-tarnish colorful for casual festive party.",
        "relatedProducts": [], "completeLook": [], "featured": False, "isNew": True, "isBestseller": True,
    },
    {
        "slug": "tinted-coral-stone-bracelet",
        "name": "Tinted Coral Stone Bracelet",
        "description": "Vibrant tinted coral stone bracelet. Anti-tarnish gold plated summer style.",
        "shortDescription": "Tinted coral stone bracelet",
        "price": 649.0, "originalPrice": 949.0, "discount": 31.0, "stock": 18,
        "rating": 4.5, "reviewCount": 65,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Most%20viral%20and%20trendy%20nail%20bracelet__%20anti-Tarnish_.jpg"],
        "category": "Bracelet", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Coral Stone", "Anti-Tarnish"], "gemstones": ["Coral"],
        "dimensions": "7 inch", "gender": ["Women"],
        "occasions": ["Casual", "Party", "Daily Wear"],
        "styleTags": ["Vibrant", "Summer", "Colorful", "Trendy"],
        "tags": ["Bracelet", "Tinted", "Coral", "Stone"], "wearType": "Wrist",
        "embeddingText": "Vibrant tinted coral stone bracelet anti-tarnish gold plated summer colorful for casual party daily wear.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-emerald-green-ring",
        "name": "Tinted Emerald Green Ring",
        "description": "Stunning tinted emerald green ring. Anti-tarnish premium silver base.",
        "shortDescription": "Tinted emerald green ring",
        "price": 749.0, "originalPrice": 1099.0, "discount": 31.0, "stock": 14,
        "rating": 4.8, "reviewCount": 88,
        "images": ["https://ik.imagekit.io/lrpk6giraj/PICK%20ANY%20TWO%20AT%20JUST%20499_-%20%E2%9C%94%EF%B8%8F_%20%20ANTI-TARNISHED%20%E2%9C%A8_.jpg"],
        "category": "Ring", "collection": "Tinted Collection",
        "materials": ["Silver", "Emerald", "Anti-Tarnish"], "gemstones": ["Emerald"],
        "dimensions": "Size 17", "gender": ["Women"],
        "occasions": ["Party", "Wedding", "Office"],
        "styleTags": ["Luxury", "Elegant", "Green", "Premium"],
        "tags": ["Ring", "Tinted", "Emerald", "Green"], "wearType": "Finger",
        "embeddingText": "Stunning tinted emerald green ring anti-tarnish premium silver luxury elegant for party wedding office.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": False, "isBestseller": True,
    },
    {
        "slug": "tinted-sapphire-blue-earrings",
        "name": "Tinted Sapphire Blue Earrings",
        "description": "Elegant tinted sapphire blue earrings. Anti-tarnish gold plated luxury feel.",
        "shortDescription": "Tinted sapphire blue earrings",
        "price": 699.0, "originalPrice": 999.0, "discount": 30.0, "stock": 16,
        "rating": 4.7, "reviewCount": 92,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Daily%20wear%20Hoops%E2%9C%A8_%20_StyleWithSpark%20Statement_.jpg"],
        "category": "Earrings", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Sapphire", "Anti-Tarnish"], "gemstones": ["Blue Sapphire"],
        "dimensions": "2.5 cm", "gender": ["Women"],
        "occasions": ["Party", "Office", "Casual"],
        "styleTags": ["Luxury", "Elegant", "Blue", "Premium"],
        "tags": ["Earrings", "Tinted", "Sapphire", "Blue"], "wearType": "Ear",
        "embeddingText": "Elegant tinted sapphire blue earrings anti-tarnish gold plated luxury for party office casual women.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-yellow-citrine-necklace",
        "name": "Tinted Yellow Citrine Necklace",
        "description": "Bright tinted yellow citrine necklace. Anti-tarnish sunshine summer vibe.",
        "shortDescription": "Tinted yellow citrine necklace",
        "price": 749.0, "originalPrice": 1099.0, "discount": 31.0, "stock": 12,
        "rating": 4.6, "reviewCount": 68,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Gold%20Plated%20Solitaire%20Pendant%20Necklace%20for%20Women_.jpg"],
        "category": "Necklace", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Citrine", "Anti-Tarnish"], "gemstones": ["Citrine"],
        "dimensions": "18 inch", "gender": ["Women"],
        "occasions": ["Casual", "Party", "Daily Wear"],
        "styleTags": ["Bright", "Sunny", "Yellow", "Trendy"],
        "tags": ["Necklace", "Tinted", "Yellow", "Citrine"], "wearType": "Neck",
        "embeddingText": "Bright tinted yellow citrine necklace anti-tarnish sunshine summer vibe for casual party daily wear.",
        "relatedProducts": [], "completeLook": [], "featured": False, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-lavender-stone-ring",
        "name": "Tinted Lavender Stone Ring",
        "description": "Delicate tinted lavender stone ring. Anti-tarnish feminine elegant style.",
        "shortDescription": "Tinted lavender stone ring",
        "price": 549.0, "originalPrice": 799.0, "discount": 31.0, "stock": 22,
        "rating": 4.6, "reviewCount": 75,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Anti-tarnished%20%20Waterproof%20%20Hypoallergenic_.jpg"],
        "category": "Ring", "collection": "Tinted Collection",
        "materials": ["Silver", "Lavender Stone", "Anti-Tarnish"], "gemstones": ["Lavender Quartz"],
        "dimensions": "Size 16", "gender": ["Women"],
        "occasions": ["Casual", "Daily Wear", "Office"],
        "styleTags": ["Feminine", "Delicate", "Lavender", "Minimal"],
        "tags": ["Ring", "Tinted", "Lavender", "Stone"], "wearType": "Finger",
        "embeddingText": "Delicate tinted lavender stone ring anti-tarnish feminine elegant minimal for casual daily wear office.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-orange-stone-bracelet",
        "name": "Tinted Orange Stone Bracelet",
        "description": "Vibrant tinted orange stone bracelet. Anti-tarnish bold colorful accessory.",
        "shortDescription": "Tinted orange stone bracelet",
        "price": 599.0, "originalPrice": 899.0, "discount": 33.0, "stock": 18,
        "rating": 4.5, "reviewCount": 62,
        "images": ["https://ik.imagekit.io/lrpk6giraj/New%20arrivals%20__%20%20Gold%20plated%20bracelets%20,%20made_.jpg"],
        "category": "Bracelet", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Orange Stone", "Anti-Tarnish"], "gemstones": ["Carnelian"],
        "dimensions": "7 inch", "gender": ["Women"],
        "occasions": ["Casual", "Party", "Festive"],
        "styleTags": ["Vibrant", "Bold", "Orange", "Trendy"],
        "tags": ["Bracelet", "Tinted", "Orange", "Stone"], "wearType": "Wrist",
        "embeddingText": "Vibrant tinted orange stone bracelet anti-tarnish bold colorful for casual party festive women.",
        "relatedProducts": [], "completeLook": [], "featured": False, "isNew": True, "isBestseller": True,
    },
    {
        "slug": "tinted-stone-set-earrings-ring",
        "name": "Tinted Stone Earrings and Ring Set",
        "description": "Matching tinted stone earrings and ring set. Anti-tarnish colorful combo.",
        "shortDescription": "Tinted stone earrings ring set",
        "price": 999.0, "originalPrice": 1499.0, "discount": 33.0, "stock": 12,
        "rating": 4.7, "reviewCount": 85,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Anti-Tarnish%20Gold-Plated%20Stainless%20Steel%20Hoop_.jpg"],
        "category": "Earrings", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Mixed Stones", "Anti-Tarnish"], "gemstones": ["Mixed"],
        "dimensions": "2 cm earrings", "gender": ["Women"],
        "occasions": ["Party", "Festive", "Casual"],
        "styleTags": ["Matching", "Colorful", "Set", "Trendy"],
        "tags": ["Set", "Earrings", "Ring", "Tinted", "Colorful"], "wearType": "Ear",
        "embeddingText": "Matching tinted stone earrings ring set anti-tarnish colorful combo for party festive casual women.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-ombre-blue-green-necklace",
        "name": "Tinted Ombre Blue Green Necklace",
        "description": "Unique tinted ombre blue-green necklace. Anti-tarnish gradient color effect.",
        "shortDescription": "Tinted ombre blue green necklace",
        "price": 849.0, "originalPrice": 1249.0, "discount": 32.0, "stock": 10,
        "rating": 4.8, "reviewCount": 72,
        "images": ["https://ik.imagekit.io/lrpk6giraj/The%20most%20wanted%20VANCLEEF%20famous%20designs%20are%20here_.jpg"],
        "category": "Necklace", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Blue-Green Stone", "Anti-Tarnish"], "gemstones": ["Aquamarine"],
        "dimensions": "18 inch", "gender": ["Women"],
        "occasions": ["Party", "Casual", "Festive"],
        "styleTags": ["Ombre", "Gradient", "Colorful", "Unique"],
        "tags": ["Necklace", "Ombre", "Blue", "Green", "Tinted"], "wearType": "Neck",
        "embeddingText": "Unique tinted ombre blue green necklace anti-tarnish gradient colorful effect for party casual festive.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": True,
    },
    {
        "slug": "tinted-ruby-red-earrings-pendant-set",
        "name": "Tinted Ruby Red Earrings Pendant Set",
        "description": "Stunning tinted ruby red earrings and pendant set. Anti-tarnish premium.",
        "shortDescription": "Tinted ruby red earrings pendant set",
        "price": 1199.0, "originalPrice": 1799.0, "discount": 33.0, "stock": 8,
        "rating": 4.9, "reviewCount": 65,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Elegant%20Gold%20Heart%20Bow%20Necklace%20%20%20Add%20a%20touch%20of_.jpg"],
        "category": "Earrings", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Ruby", "Anti-Tarnish"], "gemstones": ["Ruby"],
        "dimensions": "2.5 cm earrings", "gender": ["Women"],
        "occasions": ["Wedding", "Party", "Festive"],
        "styleTags": ["Luxury", "Bold", "Red", "Statement"],
        "tags": ["Set", "Earrings", "Pendant", "Ruby", "Tinted"], "wearType": "Ear",
        "embeddingText": "Stunning tinted ruby red earrings pendant set anti-tarnish premium luxury for wedding party festive.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": False, "isBestseller": True,
    },
    {
        "slug": "tinted-mint-green-bracelet",
        "name": "Tinted Mint Green Bracelet",
        "description": "Fresh tinted mint green bracelet. Anti-tarnish gold plated summer accessory.",
        "shortDescription": "Tinted mint green bracelet",
        "price": 549.0, "originalPrice": 799.0, "discount": 31.0, "stock": 20,
        "rating": 4.5, "reviewCount": 58,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Anti-tarnish%20everyday%20stack%20%E2%9C%A8%EF%B8%8F%20Dm%20to%20place%20order_.jpg"],
        "category": "Bracelet", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Mint Stone", "Anti-Tarnish"], "gemstones": ["Green Aventurine"],
        "dimensions": "7 inch", "gender": ["Women"],
        "occasions": ["Casual", "Daily Wear", "Party"],
        "styleTags": ["Fresh", "Mint", "Summer", "Minimal"],
        "tags": ["Bracelet", "Tinted", "Mint", "Green"], "wearType": "Wrist",
        "embeddingText": "Fresh tinted mint green bracelet anti-tarnish gold plated summer minimal for casual daily wear party.",
        "relatedProducts": [], "completeLook": [], "featured": False, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-black-onyx-ring",
        "name": "Tinted Black Onyx Ring",
        "description": "Sleek tinted black onyx ring. Anti-tarnish edgy minimalist design.",
        "shortDescription": "Tinted black onyx ring",
        "price": 649.0, "originalPrice": 949.0, "discount": 31.0, "stock": 20,
        "rating": 4.7, "reviewCount": 95,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Stainless%20steel%20bracelet%20%E2%9C%A8%20-%2018%20k%20gold%20plated_.jpg"],
        "category": "Ring", "collection": "Tinted Collection",
        "materials": ["Silver", "Black Onyx", "Anti-Tarnish"], "gemstones": ["Black Onyx"],
        "dimensions": "Size 17", "gender": ["Women", "Unisex"],
        "occasions": ["Daily Wear", "Office", "Casual"],
        "styleTags": ["Edgy", "Minimal", "Black", "Modern"],
        "tags": ["Ring", "Tinted", "Black", "Onyx"], "wearType": "Finger",
        "embeddingText": "Sleek tinted black onyx ring anti-tarnish edgy minimalist modern for daily wear office casual.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": True,
    },
    {
        "slug": "tinted-peach-stone-necklace",
        "name": "Tinted Peach Stone Necklace",
        "description": "Soft tinted peach stone necklace. Anti-tarnish romantic feminine style.",
        "shortDescription": "Tinted peach stone necklace",
        "price": 699.0, "originalPrice": 999.0, "discount": 30.0, "stock": 14,
        "rating": 4.6, "reviewCount": 68,
        "images": ["https://ik.imagekit.io/lrpk6giraj/18K%20Gold%20Plated%20Bow%20Pendant%20Necklace%20for%20Women_.jpg"],
        "category": "Necklace", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Peach Stone", "Anti-Tarnish"], "gemstones": ["Peach Moonstone"],
        "dimensions": "18 inch", "gender": ["Women"],
        "occasions": ["Casual", "Party", "Valentine"],
        "styleTags": ["Romantic", "Feminine", "Peach", "Soft"],
        "tags": ["Necklace", "Tinted", "Peach", "Stone"], "wearType": "Neck",
        "embeddingText": "Soft tinted peach stone necklace anti-tarnish romantic feminine for casual party valentine women.",
        "relatedProducts": [], "completeLook": [], "featured": False, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-sky-blue-earrings-set",
        "name": "Tinted Sky Blue Earrings Set",
        "description": "Elegant tinted sky blue earrings set. Anti-tarnish fresh ocean vibe.",
        "shortDescription": "Tinted sky blue earrings set",
        "price": 599.0, "originalPrice": 899.0, "discount": 33.0, "stock": 18,
        "rating": 4.6, "reviewCount": 78,
        "images": ["https://ik.imagekit.io/lrpk6giraj/%E2%9C%A8%20Everyday%20Elegance%20%E2%9C%A8_Water-Resistant_.jpg"],
        "category": "Earrings", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Sky Blue Stone", "Anti-Tarnish"], "gemstones": ["Blue Topaz"],
        "dimensions": "2 cm", "gender": ["Women"],
        "occasions": ["Daily Wear", "Casual", "Office"],
        "styleTags": ["Fresh", "Ocean", "Blue", "Elegant"],
        "tags": ["Earrings", "Tinted", "Sky Blue", "Stone"], "wearType": "Ear",
        "embeddingText": "Elegant tinted sky blue earrings anti-tarnish fresh ocean vibe for daily wear casual office women.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-gold-stone-bangles-set",
        "name": "Tinted Gold Stone Bangles Set",
        "description": "Beautiful tinted gold stone bangles set of 4. Anti-tarnish festive collection.",
        "shortDescription": "Tinted gold stone bangles set",
        "price": 899.0, "originalPrice": 1299.0, "discount": 30.0, "stock": 12,
        "rating": 4.7, "reviewCount": 82,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Golden%20essentials%20___Shop%20the%20entire%20collection_.jpg"],
        "category": "Bangle", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Gold Stone", "Anti-Tarnish"], "gemstones": ["Golden Topaz"],
        "dimensions": "2.6 size", "gender": ["Women"],
        "occasions": ["Festive", "Wedding", "Party"],
        "styleTags": ["Festive", "Gold", "Set", "Premium"],
        "tags": ["Bangle", "Set", "Tinted", "Gold Stone"], "wearType": "Wrist",
        "embeddingText": "Beautiful tinted gold stone bangles set anti-tarnish festive premium for wedding party festive women.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": False, "isBestseller": True,
    },
    {
        "slug": "tinted-rose-pink-ring-set",
        "name": "Tinted Rose Pink Ring Set",
        "description": "Romantic tinted rose pink ring set of 2. Anti-tarnish couple style.",
        "shortDescription": "Tinted rose pink ring set",
        "price": 799.0, "originalPrice": 1199.0, "discount": 33.0, "stock": 15,
        "rating": 4.8, "reviewCount": 88,
        "images": ["https://ik.imagekit.io/lrpk6giraj/SALVE%20Clover%20Anti%20Tarnish%20Bracelet%20for%20Women_.jpg"],
        "category": "Ring", "collection": "Tinted Collection",
        "materials": ["Silver", "Rose Quartz", "Anti-Tarnish"], "gemstones": ["Rose Quartz"],
        "dimensions": "Size 16-17", "gender": ["Women"],
        "occasions": ["Valentine", "Anniversary", "Casual"],
        "styleTags": ["Romantic", "Pink", "Couple", "Set"],
        "tags": ["Ring", "Set", "Tinted", "Rose Pink"], "wearType": "Finger",
        "embeddingText": "Romantic tinted rose pink ring set anti-tarnish couple style for valentine anniversary casual women.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-aqua-green-pendant",
        "name": "Tinted Aqua Green Pendant Necklace",
        "description": "Refreshing tinted aqua green pendant necklace. Anti-tarnish ocean inspired.",
        "shortDescription": "Tinted aqua green pendant",
        "price": 649.0, "originalPrice": 949.0, "discount": 31.0, "stock": 16,
        "rating": 4.6, "reviewCount": 70,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Complete%20your%20look%20with%20these%20simple%20anti_.jpg"],
        "category": "Pendant", "collection": "Tinted Collection",
        "materials": ["Silver", "Aqua Stone", "Anti-Tarnish"], "gemstones": ["Aquamarine"],
        "dimensions": "18 inch chain", "gender": ["Women"],
        "occasions": ["Casual", "Daily Wear", "Party"],
        "styleTags": ["Ocean", "Aqua", "Fresh", "Minimal"],
        "tags": ["Pendant", "Tinted", "Aqua", "Green"], "wearType": "Neck",
        "embeddingText": "Refreshing tinted aqua green pendant necklace anti-tarnish ocean inspired for casual daily wear party.",
        "relatedProducts": [], "completeLook": [], "featured": False, "isNew": True, "isBestseller": True,
    },
    {
        "slug": "tinted-dusty-rose-earrings",
        "name": "Tinted Dusty Rose Earrings",
        "description": "Elegant tinted dusty rose earrings. Anti-tarnish muted pink boho style.",
        "shortDescription": "Tinted dusty rose earrings",
        "price": 499.0, "originalPrice": 749.0, "discount": 33.0, "stock": 22,
        "rating": 4.5, "reviewCount": 82,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Say%20goodbye%20to%20dull,%20tarnished%20jewelry!%20These_.jpg"],
        "category": "Earrings", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Dusty Rose Stone", "Anti-Tarnish"], "gemstones": ["Pink Quartz"],
        "dimensions": "2 cm", "gender": ["Women"],
        "occasions": ["Casual", "Daily Wear", "Office"],
        "styleTags": ["Boho", "Muted", "Pink", "Elegant"],
        "tags": ["Earrings", "Tinted", "Dusty Rose", "Pink"], "wearType": "Ear",
        "embeddingText": "Elegant tinted dusty rose earrings anti-tarnish muted pink boho for casual daily wear office women.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-jade-green-bracelet",
        "name": "Tinted Jade Green Bracelet",
        "description": "Lucky tinted jade green bracelet. Anti-tarnish good luck charm style.",
        "shortDescription": "Tinted jade green bracelet",
        "price": 699.0, "originalPrice": 999.0, "discount": 30.0, "stock": 14,
        "rating": 4.7, "reviewCount": 62,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Chic%20and%20a%20truly%20a%20must%20have%20piece_%20Stack%20it%20up%20or_.jpg"],
        "category": "Bracelet", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Jade", "Anti-Tarnish"], "gemstones": ["Jade"],
        "dimensions": "7 inch", "gender": ["Women"],
        "occasions": ["Daily Wear", "Casual", "Gifting"],
        "styleTags": ["Lucky", "Jade", "Green", "Natural"],
        "tags": ["Bracelet", "Tinted", "Jade", "Green"], "wearType": "Wrist",
        "embeddingText": "Lucky tinted jade green bracelet anti-tarnish good luck charm natural for daily wear casual gifting.",
        "relatedProducts": [], "completeLook": [], "featured": False, "isNew": True, "isBestseller": True,
    },
    {
        "slug": "tinted-crystal-clear-necklace",
        "name": "Tinted Crystal Clear Necklace",
        "description": "Elegant tinted crystal clear necklace. Anti-tarnish diamond-like sparkle.",
        "shortDescription": "Tinted crystal clear necklace",
        "price": 749.0, "originalPrice": 1099.0, "discount": 31.0, "stock": 18,
        "rating": 4.8, "reviewCount": 110,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Necklaces%20for%20everyday%20use%20_%E2%9D%A4%EF%B8%8F%20%20%E2%82%B9850%20each%20plus_.jpg"],
        "category": "Necklace", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Crystal", "Anti-Tarnish"], "gemstones": ["Crystal"],
        "dimensions": "18 inch", "gender": ["Women"],
        "occasions": ["Party", "Daily Wear", "Office"],
        "styleTags": ["Sparkle", "Crystal", "Elegant", "Premium"],
        "tags": ["Necklace", "Tinted", "Crystal", "Clear"], "wearType": "Neck",
        "embeddingText": "Elegant tinted crystal clear necklace anti-tarnish diamond sparkle premium for party daily wear office.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": True,
    },
    {
        "slug": "tinted-navy-blue-bangle",
        "name": "Tinted Navy Blue Bangle",
        "description": "Sophisticated tinted navy blue bangle. Anti-tarnish deep blue statement piece.",
        "shortDescription": "Tinted navy blue bangle",
        "price": 649.0, "originalPrice": 949.0, "discount": 31.0, "stock": 15,
        "rating": 4.6, "reviewCount": 55,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Anti-Tarnished%20jwellery%20%E2%9C%A8.jpg"],
        "category": "Bangle", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Navy Blue Stone", "Anti-Tarnish"], "gemstones": ["Lapis Lazuli"],
        "dimensions": "2.6 size", "gender": ["Women"],
        "occasions": ["Party", "Festive", "Office"],
        "styleTags": ["Sophisticated", "Navy", "Blue", "Statement"],
        "tags": ["Bangle", "Tinted", "Navy Blue", "Statement"], "wearType": "Wrist",
        "embeddingText": "Sophisticated tinted navy blue bangle anti-tarnish deep blue statement for party festive office women.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": False, "isBestseller": False,
    },
    {
        "slug": "tinted-rainbow-stone-ring",
        "name": "Tinted Rainbow Stone Ring",
        "description": "Playful tinted rainbow stone ring. Anti-tarnish colorful fun accessory.",
        "shortDescription": "Tinted rainbow stone ring",
        "price": 499.0, "originalPrice": 749.0, "discount": 33.0, "stock": 25,
        "rating": 4.5, "reviewCount": 92,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Premium%20anti%20Tarnished%20Jewellery%20_%20Stainless%20steel_.jpg"],
        "category": "Ring", "collection": "Tinted Collection",
        "materials": ["Silver", "Rainbow Stone", "Anti-Tarnish"], "gemstones": ["Mixed Gemstones"],
        "dimensions": "Size 16", "gender": ["Women"],
        "occasions": ["Casual", "Party", "Daily Wear"],
        "styleTags": ["Playful", "Rainbow", "Fun", "Colorful"],
        "tags": ["Ring", "Tinted", "Rainbow", "Colorful"], "wearType": "Finger",
        "embeddingText": "Playful tinted rainbow stone ring anti-tarnish colorful fun accessory for casual party daily wear.",
        "relatedProducts": [], "completeLook": [], "featured": False, "isNew": True, "isBestseller": True,
    },
    {
        "slug": "tinted-golden-yellow-earrings",
        "name": "Tinted Golden Yellow Earrings",
        "description": "Radiant tinted golden yellow stone earrings. Anti-tarnish sunny cheerful style.",
        "shortDescription": "Tinted golden yellow earrings",
        "price": 549.0, "originalPrice": 799.0, "discount": 31.0, "stock": 20,
        "rating": 4.6, "reviewCount": 75,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Anti%20Tarnished%20_%20Premium%20Quality%20Heart%20Necklace_.jpg"],
        "category": "Earrings", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Yellow Stone", "Anti-Tarnish"], "gemstones": ["Yellow Topaz"],
        "dimensions": "2 cm", "gender": ["Women"],
        "occasions": ["Daily Wear", "Festive", "Casual"],
        "styleTags": ["Radiant", "Sunny", "Yellow", "Cheerful"],
        "tags": ["Earrings", "Tinted", "Golden", "Yellow"], "wearType": "Ear",
        "embeddingText": "Radiant tinted golden yellow stone earrings anti-tarnish sunny cheerful for daily wear festive casual.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-stone-necklace-bracelet-set",
        "name": "Tinted Stone Necklace Bracelet Set",
        "description": "Complete tinted stone necklace and bracelet set. Anti-tarnish colorful combo.",
        "shortDescription": "Tinted stone necklace bracelet set",
        "price": 1299.0, "originalPrice": 1899.0, "discount": 31.0, "stock": 8,
        "rating": 4.8, "reviewCount": 68,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Swipe%20Right%20%E2%96%B6%EF%B8%8F%20%20%20Delivery%20PAN%20India%20_%20%20%20DM%20to_.jpg"],
        "category": "Necklace", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Mixed Stones", "Anti-Tarnish"], "gemstones": ["Mixed"],
        "dimensions": "18 inch", "gender": ["Women"],
        "occasions": ["Party", "Festive", "Gifting"],
        "styleTags": ["Complete", "Colorful", "Set", "Premium"],
        "tags": ["Set", "Necklace", "Bracelet", "Tinted", "Stone"], "wearType": "Neck",
        "embeddingText": "Complete tinted stone necklace bracelet set anti-tarnish colorful combo for party festive gifting.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": True,
    },
    {
        "slug": "tinted-white-pearl-ring",
        "name": "Tinted White Pearl Ring",
        "description": "Elegant tinted white pearl ring. Anti-tarnish classic feminine style.",
        "shortDescription": "Tinted white pearl ring",
        "price": 699.0, "originalPrice": 999.0, "discount": 30.0, "stock": 18,
        "rating": 4.7, "reviewCount": 88,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Welcome%20to%20_%20Zivra%20Jewellery__%20our%20channel%20is%20all_.jpg"],
        "category": "Ring", "collection": "Tinted Collection",
        "materials": ["Silver", "Pearl", "Anti-Tarnish"], "gemstones": ["Pearl"],
        "dimensions": "Size 17", "gender": ["Women"],
        "occasions": ["Wedding", "Office", "Formal"],
        "styleTags": ["Classic", "Feminine", "Pearl", "Elegant"],
        "tags": ["Ring", "Tinted", "White", "Pearl"], "wearType": "Finger",
        "embeddingText": "Elegant tinted white pearl ring anti-tarnish classic feminine for wedding office formal women.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": False, "isBestseller": True,
    },
    {
        "slug": "tinted-sunset-orange-necklace",
        "name": "Tinted Sunset Orange Necklace",
        "description": "Warm tinted sunset orange necklace. Anti-tarnish earthy boho autumn style.",
        "shortDescription": "Tinted sunset orange necklace",
        "price": 749.0, "originalPrice": 1099.0, "discount": 31.0, "stock": 12,
        "rating": 4.6, "reviewCount": 62,
        "images": ["https://ik.imagekit.io/lrpk6giraj/zivra-anti-tarnish-jewelry-channel.jpg"] if False else ["https://ik.imagekit.io/lrpk6giraj/576883033558963555.jpg"],
        "category": "Necklace", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Orange Stone", "Anti-Tarnish"], "gemstones": ["Sunstone"],
        "dimensions": "18 inch", "gender": ["Women"],
        "occasions": ["Casual", "Party", "Festive"],
        "styleTags": ["Warm", "Boho", "Autumn", "Earthy"],
        "tags": ["Necklace", "Tinted", "Sunset", "Orange"], "wearType": "Neck",
        "embeddingText": "Warm tinted sunset orange necklace anti-tarnish earthy boho autumn style for casual party festive.",
        "relatedProducts": [], "completeLook": [], "featured": False, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-ice-blue-bracelet",
        "name": "Tinted Ice Blue Bracelet",
        "description": "Cool tinted ice blue bracelet. Anti-tarnish winter minimal chic style.",
        "shortDescription": "Tinted ice blue bracelet",
        "price": 599.0, "originalPrice": 899.0, "discount": 33.0, "stock": 16,
        "rating": 4.5, "reviewCount": 58,
        "images": ["https://ik.imagekit.io/lrpk6giraj/121597258686035582.jpg"],
        "category": "Bracelet", "collection": "Tinted Collection",
        "materials": ["Silver", "Blue Stone", "Anti-Tarnish"], "gemstones": ["Blue Chalcedony"],
        "dimensions": "7 inch", "gender": ["Women"],
        "occasions": ["Daily Wear", "Casual", "Office"],
        "styleTags": ["Cool", "Ice Blue", "Minimal", "Chic"],
        "tags": ["Bracelet", "Tinted", "Ice Blue", "Stone"], "wearType": "Wrist",
        "embeddingText": "Cool tinted ice blue bracelet anti-tarnish winter minimal chic for daily wear casual office women.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-champagne-stone-earrings",
        "name": "Tinted Champagne Stone Earrings",
        "description": "Luxurious tinted champagne stone earrings. Anti-tarnish nude glam style.",
        "shortDescription": "Tinted champagne stone earrings",
        "price": 699.0, "originalPrice": 999.0, "discount": 30.0, "stock": 14,
        "rating": 4.7, "reviewCount": 72,
        "images": ["https://ik.imagekit.io/lrpk6giraj/483011128805724284.jpg"],
        "category": "Earrings", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Champagne Stone", "Anti-Tarnish"], "gemstones": ["Champagne Quartz"],
        "dimensions": "2.5 cm", "gender": ["Women"],
        "occasions": ["Party", "Formal", "Office"],
        "styleTags": ["Nude Glam", "Luxurious", "Champagne", "Elegant"],
        "tags": ["Earrings", "Tinted", "Champagne", "Stone"], "wearType": "Ear",
        "embeddingText": "Luxurious tinted champagne stone earrings anti-tarnish nude glam elegant for party formal office.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": False, "isBestseller": True,
    },
    {
        "slug": "tinted-forest-green-pendant",
        "name": "Tinted Forest Green Pendant",
        "description": "Deep tinted forest green pendant necklace. Anti-tarnish nature inspired.",
        "shortDescription": "Tinted forest green pendant",
        "price": 649.0, "originalPrice": 949.0, "discount": 31.0, "stock": 15,
        "rating": 4.6, "reviewCount": 65,
        "images": ["https://ik.imagekit.io/lrpk6giraj/63261569762461590.jpg"],
        "category": "Pendant", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Green Stone", "Anti-Tarnish"], "gemstones": ["Malachite"],
        "dimensions": "18 inch chain", "gender": ["Women"],
        "occasions": ["Casual", "Daily Wear", "Party"],
        "styleTags": ["Nature", "Forest", "Green", "Earthy"],
        "tags": ["Pendant", "Tinted", "Forest", "Green"], "wearType": "Neck",
        "embeddingText": "Deep tinted forest green pendant necklace anti-tarnish nature inspired earthy for casual daily wear party.",
        "relatedProducts": [], "completeLook": [], "featured": False, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-blush-pink-ring-pendant-set",
        "name": "Tinted Blush Pink Ring Pendant Set",
        "description": "Romantic tinted blush pink ring and pendant set. Anti-tarnish feminine combo.",
        "shortDescription": "Tinted blush pink ring pendant set",
        "price": 1099.0, "originalPrice": 1599.0, "discount": 31.0, "stock": 10,
        "rating": 4.8, "reviewCount": 85,
        "images": ["https://ik.imagekit.io/lrpk6giraj/761389880805672039.jpg"],
        "category": "Ring", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Pink Stone", "Anti-Tarnish"], "gemstones": ["Rose Quartz"],
        "dimensions": "Size 16", "gender": ["Women"],
        "occasions": ["Valentine", "Anniversary", "Party"],
        "styleTags": ["Romantic", "Blush", "Pink", "Feminine"],
        "tags": ["Set", "Ring", "Pendant", "Tinted", "Pink"], "wearType": "Finger",
        "embeddingText": "Romantic tinted blush pink ring pendant set anti-tarnish feminine for valentine anniversary party.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": False,
    },
    {
        "slug": "tinted-electric-blue-bracelet-set",
        "name": "Tinted Electric Blue Bracelet Set",
        "description": "Bold tinted electric blue bracelet set. Anti-tarnish vibrant statement.",
        "shortDescription": "Tinted electric blue bracelet set",
        "price": 899.0, "originalPrice": 1299.0, "discount": 30.0, "stock": 10,
        "rating": 4.7, "reviewCount": 58,
        "images": ["https://ik.imagekit.io/lrpk6giraj/878764946057751244.jpg"],
        "category": "Bracelet", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Electric Blue Stone", "Anti-Tarnish"], "gemstones": ["Blue Agate"],
        "dimensions": "7 inch", "gender": ["Women"],
        "occasions": ["Party", "Festive", "Casual"],
        "styleTags": ["Bold", "Electric", "Blue", "Statement"],
        "tags": ["Bracelet", "Set", "Tinted", "Electric Blue"], "wearType": "Wrist",
        "embeddingText": "Bold tinted electric blue bracelet set anti-tarnish vibrant statement for party festive casual women.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": True,
    },
    {
        "slug": "tinted-mauve-purple-necklace",
        "name": "Tinted Mauve Purple Necklace",
        "description": "Dreamy tinted mauve purple necklace. Anti-tarnish romantic celestial vibe.",
        "shortDescription": "Tinted mauve purple necklace",
        "price": 749.0, "originalPrice": 1099.0, "discount": 31.0, "stock": 12,
        "rating": 4.7, "reviewCount": 72,
        "images": ["https://ik.imagekit.io/lrpk6giraj/910571619579968395.jpg"],
        "category": "Necklace", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Purple Stone", "Anti-Tarnish"], "gemstones": ["Amethyst"],
        "dimensions": "18 inch", "gender": ["Women"],
        "occasions": ["Party", "Casual", "Gifting"],
        "styleTags": ["Dreamy", "Romantic", "Mauve", "Celestial"],
        "tags": ["Necklace", "Tinted", "Mauve", "Purple"], "wearType": "Neck",
        "embeddingText": "Dreamy tinted mauve purple necklace anti-tarnish romantic celestial vibe for party casual gifting.",
        "relatedProducts": [], "completeLook": [], "featured": False, "isNew": True, "isBestseller": True,
    },
    {
        "slug": "tinted-colorful-stone-full-set",
        "name": "Tinted Colorful Stone Full Jewelry Set",
        "description": "Complete tinted colorful stone full jewelry set. Anti-tarnish festive statement.",
        "shortDescription": "Tinted colorful full jewelry set",
        "price": 1799.0, "originalPrice": 2599.0, "discount": 30.0, "stock": 6,
        "rating": 4.9, "reviewCount": 55,
        "images": ["https://ik.imagekit.io/lrpk6giraj/617063586484321679.jpg"],
        "category": "Necklace", "collection": "Tinted Collection",
        "materials": ["Gold Plated", "Mixed Stones", "Anti-Tarnish"], "gemstones": ["Mixed Gemstones"],
        "dimensions": "18 inch", "gender": ["Women"],
        "occasions": ["Wedding", "Festive", "Party"],
        "styleTags": ["Complete", "Colorful", "Statement", "Premium"],
        "tags": ["Set", "Full", "Tinted", "Colorful", "Stone"], "wearType": "Neck",
        "embeddingText": "Complete tinted colorful stone full jewelry set anti-tarnish festive statement premium for wedding party.",
        "relatedProducts": [], "completeLook": [], "featured": True, "isNew": True, "isBestseller": True,
    },
]


def seed():
    print("🌱 Seeding database...")
    create_tables()
    db = SessionLocal()

    created = []
    for p in PRODUCTS:
        try:
            product = create_product(db, p)
            created.append(product)
            print(f"  ✅ {product.name}")
        except Exception as e:
            print(f"  ⚠️  {p['name']}: {e}")

    print(f"\n✅ {len(created)} products seeded to PostgreSQL")

    # Product dicts pehle banao — db.close() se PEHLE
    product_dicts = [
        {
            "id":            p.id,
            "embeddingText": p.embedding_text,
            "category":      p.category,
            "materials":     p.materials or [],
            "occasions":     p.occasions or [],
            "styleTags":     p.style_tags or [],
            "wearType":      p.wear_type or "",
            "gender":        p.gender or [],
            "price":         p.price,
            "featured":      p.featured,
        }
        for p in created
    ]

    db.close()  # ✅ Ab close karo

    # Sync to Pinecone
    print("\n🔗 Syncing to Pinecone...")
    result = bulk_upsert_products(product_dicts)
    print(f"✅ Pinecone: {result['message']}")


if __name__ == "__main__":
    seed()