"""
Seed Script — Éclat Platform
Inserts sample products into PostgreSQL and syncs to Pinecone.
Run: python -m scripts.seed_products
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.database.connection import SessionLocal, create_tables
from app.products.product_service import create_product
from app.chatbot.pinecone_service import bulk_upsert_products

PRODUCTS = [
    {
        "slug": "diamond-solitaire-necklace",
        "name": "Diamond Solitaire Pendant",
        "description": "A breathtaking 0.5ct round brilliant diamond suspended on an 18K gold chain. Timeless. Unapologetically beautiful.",
        "shortDescription": "0.5ct round brilliant diamond on 18K gold chain.",
        "price": 145000,
        "stock": 8,
        "images": [
            "https://ik.imagekit.io/eclat/diamond-solitaire-1.jpg",
            "https://ik.imagekit.io/eclat/diamond-solitaire-2.jpg",
        ],
        "category": "necklace",
        "collection": "Eternal",
        "materials": ["gold", "diamond"],
        "gemstones": ["diamond"],
        "gender": ["female", "unisex"],
        "occasions": ["wedding", "anniversary", "gifting"],
        "styleTags": ["timeless", "elegant", "luxury", "bridal"],
        "tags": ["diamond", "necklace", "gold", "bridal"],
        "wearType": "neck",
        "embeddingText": "Elegant 18K gold diamond solitaire necklace designed for wedding and anniversary occasions with timeless luxury aesthetics and bridal elegance for women",
        "relatedProducts": [],
        "completeLook": [],
        "featured": True,
        "isNew": False,
        "isBestseller": True,
        "rating": 4.9,
        "reviewCount": 127,
    },
    {
        "slug": "minimal-gold-link-bracelet",
        "name": "Minimal Gold Link Bracelet",
        "description": "Delicate 18K yellow gold links crafted for everyday luxury. A whisper of gold around the wrist.",
        "shortDescription": "18K yellow gold everyday bracelet.",
        "price": 38500,
        "stock": 14,
        "images": ["https://ik.imagekit.io/eclat/gold-bracelet-1.jpg"],
        "category": "bracelet",
        "collection": "Quotidien",
        "materials": ["gold"],
        "gemstones": [],
        "gender": ["female", "unisex"],
        "occasions": ["daily", "gifting", "anniversary"],
        "styleTags": ["minimal", "contemporary", "everyday"],
        "tags": ["gold", "bracelet", "minimal"],
        "wearType": "hands",
        "embeddingText": "Minimal 18K yellow gold link bracelet for everyday wear, contemporary design, lightweight, perfect gifting piece for women",
        "relatedProducts": [],
        "completeLook": [],
        "featured": False,
        "isNew": True,
        "isBestseller": False,
        "rating": 4.7,
        "reviewCount": 89,
    },
    {
        "slug": "ruby-drop-earrings",
        "name": "Ruby Pavé Drop Earrings",
        "description": "Deep Burmese rubies set in a cascading pavé drop. Designed for the woman who enters a room and changes it.",
        "shortDescription": "Burmese rubies in 18K gold pavé drop setting.",
        "price": 89000,
        "stock": 5,
        "images": ["https://ik.imagekit.io/eclat/ruby-earrings-1.jpg"],
        "category": "earrings",
        "collection": "Lumière Rouge",
        "materials": ["gold", "ruby"],
        "gemstones": ["ruby"],
        "gender": ["female"],
        "occasions": ["wedding", "party", "festive"],
        "styleTags": ["bold", "dramatic", "luxury", "statement"],
        "tags": ["ruby", "earrings", "statement"],
        "wearType": "ears",
        "embeddingText": "Bold ruby pavé drop earrings in 18K gold for weddings and special occasions, dramatic statement jewellery for women who command attention",
        "relatedProducts": [],
        "completeLook": [],
        "featured": True,
        "isNew": False,
        "isBestseller": False,
        "rating": 4.8,
        "reviewCount": 43,
    },
    {
        "slug": "emerald-cocktail-ring",
        "name": "Emerald Cocktail Ring",
        "description": "A 3ct Colombian emerald, cathedral-set in 18K white gold with diamond shoulders. Bold. Intentional. Unforgettable.",
        "shortDescription": "3ct Colombian emerald in 18K white gold with diamond shoulders.",
        "price": 210000,
        "stock": 3,
        "images": ["https://ik.imagekit.io/eclat/emerald-ring-1.jpg"],
        "category": "ring",
        "collection": "Vivid",
        "materials": ["white gold", "diamond", "emerald"],
        "gemstones": ["emerald", "diamond"],
        "gender": ["female"],
        "occasions": ["party", "anniversary", "gifting"],
        "styleTags": ["bold", "luxury", "statement", "cocktail"],
        "tags": ["emerald", "ring", "statement", "diamond"],
        "wearType": "rings",
        "embeddingText": "Bold emerald cocktail ring 3ct Colombian emerald 18K white gold diamond shoulders luxury statement jewellery for women anniversary party",
        "relatedProducts": [],
        "completeLook": [],
        "featured": True,
        "isNew": False,
        "isBestseller": True,
        "rating": 5.0,
        "reviewCount": 18,
    },
    {
        "slug": "platinum-solitaire-band",
        "name": "Platinum Solitaire Band",
        "description": "A full-circle pavé of round brilliants set in platinum. Every angle, a new constellation.",
        "shortDescription": "Full pavé diamond eternity band in platinum.",
        "price": 175000,
        "stock": 6,
        "images": ["https://ik.imagekit.io/eclat/platinum-band-1.jpg"],
        "category": "ring",
        "collection": "Eternal",
        "materials": ["platinum", "diamond"],
        "gemstones": ["diamond"],
        "gender": ["female", "unisex"],
        "occasions": ["wedding", "anniversary"],
        "styleTags": ["timeless", "elegant", "bridal", "minimal"],
        "tags": ["platinum", "ring", "diamond", "eternity"],
        "wearType": "rings",
        "embeddingText": "Platinum pavé diamond eternity band ring for wedding bridal engagement timeless elegant minimal design for women",
        "relatedProducts": [],
        "completeLook": [],
        "featured": False,
        "isNew": False,
        "isBestseller": True,
        "rating": 4.9,
        "reviewCount": 211,
    },
    {
        "slug": "rose-gold-layered-necklace",
        "name": "Rose Gold Layered Necklace",
        "description": "Three delicate chains of 18K rose gold, lengths curated to fall in perfect asymmetry. The everyday luxe.",
        "shortDescription": "Three-tier 18K rose gold layered chain necklace.",
        "price": 52000,
        "stock": 9,
        "images": ["https://ik.imagekit.io/eclat/rose-gold-necklace-1.jpg"],
        "category": "necklace",
        "collection": "Quotidien",
        "materials": ["rose gold"],
        "gemstones": [],
        "gender": ["female"],
        "occasions": ["daily", "gifting", "anniversary"],
        "styleTags": ["romantic", "feminine", "layered", "contemporary"],
        "tags": ["rose gold", "necklace", "layered", "daily"],
        "wearType": "neck",
        "embeddingText": "Romantic rose gold layered necklace three chains feminine contemporary everyday luxury wear for women gifting anniversary",
        "relatedProducts": [],
        "completeLook": [],
        "featured": False,
        "isNew": True,
        "isBestseller": False,
        "rating": 4.6,
        "reviewCount": 64,
    },
    {
        "slug": "silver-hoop-earrings-minimal",
        "name": "Sterling Silver Architectural Hoops",
        "description": "Oversized, polished, architectural. These hoops don't just hang — they declare.",
        "shortDescription": "Oversized polished sterling silver hoop earrings.",
        "price": 12500,
        "stock": 22,
        "images": ["https://ik.imagekit.io/eclat/silver-hoops-1.jpg"],
        "category": "earrings",
        "collection": "Structure",
        "materials": ["silver"],
        "gemstones": [],
        "gender": ["female", "unisex"],
        "occasions": ["daily", "party"],
        "styleTags": ["minimal", "architectural", "editorial", "modern"],
        "tags": ["silver", "earrings", "hoop", "minimal"],
        "wearType": "ears",
        "embeddingText": "Minimal architectural oversized sterling silver hoop earrings editorial modern contemporary daily wear statement jewellery",
        "relatedProducts": [],
        "completeLook": [],
        "featured": False,
        "isNew": True,
        "isBestseller": False,
        "rating": 4.5,
        "reviewCount": 156,
    },
    {
        "slug": "mens-gold-chain-bold",
        "name": "Men's Cuban Link Chain",
        "description": "Substantial 18K yellow gold Cuban links. Heavyweight presence. Worn alone or over a shirt — it always commands.",
        "shortDescription": "Heavy 18K yellow gold Cuban link chain for men.",
        "price": 285000,
        "stock": 4,
        "images": ["https://ik.imagekit.io/eclat/mens-chain-1.jpg"],
        "category": "necklace",
        "collection": "Prestige",
        "materials": ["gold"],
        "gemstones": [],
        "gender": ["male", "unisex"],
        "occasions": ["daily", "party"],
        "styleTags": ["bold", "luxury", "statement", "heavyweight"],
        "tags": ["gold", "chain", "men", "bold"],
        "wearType": "neck",
        "embeddingText": "Bold heavyweight 18K gold Cuban link chain for men luxury statement necklace strong masculine daily wear party",
        "relatedProducts": [],
        "completeLook": [],
        "featured": True,
        "isNew": False,
        "isBestseller": False,
        "rating": 4.8,
        "reviewCount": 37,
    },
    {
        "slug": "sapphire-tennis-bracelet",
        "name": "Blue Sapphire Tennis Bracelet",
        "description": "Ceylon sapphires in a seamless prong-set line of 18K white gold. The tennis bracelet, reimagined with colour.",
        "shortDescription": "Ceylon sapphire tennis bracelet in 18K white gold.",
        "price": 132000,
        "stock": 7,
        "images": ["https://ik.imagekit.io/eclat/sapphire-bracelet-1.jpg"],
        "category": "bracelet",
        "collection": "Vivid",
        "materials": ["white gold", "sapphire"],
        "gemstones": ["sapphire"],
        "gender": ["female"],
        "occasions": ["wedding", "anniversary", "party"],
        "styleTags": ["elegant", "luxury", "timeless", "bridal"],
        "tags": ["sapphire", "bracelet", "white gold", "tennis"],
        "wearType": "hands",
        "embeddingText": "Blue sapphire tennis bracelet 18K white gold elegant timeless luxury bridal wedding anniversary women statement",
        "relatedProducts": [],
        "completeLook": [],
        "featured": False,
        "isNew": False,
        "isBestseller": False,
        "rating": 4.9,
        "reviewCount": 29,
    },
    {
        "slug": "diamond-stud-earrings-classic",
        "name": "Classic Diamond Stud Earrings",
        "description": "0.5ct each. Round brilliants. Four-claw platinum setting. The earrings every woman deserves to own.",
        "shortDescription": "0.5ct diamond studs in four-claw platinum setting.",
        "price": 95000,
        "stock": 12,
        "images": ["https://ik.imagekit.io/eclat/diamond-studs-1.jpg"],
        "category": "earrings",
        "collection": "Eternal",
        "materials": ["platinum", "diamond"],
        "gemstones": ["diamond"],
        "gender": ["female", "unisex"],
        "occasions": ["daily", "wedding", "gifting", "anniversary"],
        "styleTags": ["classic", "timeless", "elegant", "minimal"],
        "tags": ["diamond", "studs", "earrings", "classic"],
        "wearType": "ears",
        "embeddingText": "Classic diamond stud earrings 0.5ct round brilliant platinum four claw setting timeless elegant daily wear gifting women anniversary wedding",
        "relatedProducts": [],
        "completeLook": [],
        "featured": True,
        "isNew": False,
        "isBestseller": True,
        "rating": 4.9,
        "reviewCount": 342,
    },
]


def seed():
    print("🌱 Seeding database...")
    create_tables()
    db = SessionLocal()

    created = []
    for p in PRODUCTS:
        try:
            product = create_product(db, p)
            created.append(product)
            print(f"  ✅ {product.name}")
        except Exception as e:
            print(f"  ⚠️  {p['name']}: {e}")

    db.close()
    print(f"\n✅ {len(created)} products seeded to PostgreSQL")

    # Sync to Pinecone
    print("\n🔗 Syncing to Pinecone...")
    product_dicts = [
        {
            "id":            p.id,
            "embeddingText": p.embedding_text,
            "category":      p.category,
            "materials":     p.materials or [],
            "occasions":     p.occasions or [],
            "styleTags":     p.style_tags or [],
            "wearType":      p.wear_type or "",
            "gender":        p.gender or [],
            "price":         p.price,
            "featured":      p.featured,
        }
        for p in created
    ]

    result = bulk_upsert_products(product_dicts)
    print(f"✅ Pinecone: {result['message']}")


if __name__ == "__main__":
    seed()