# ======================================================
# INSERT PRODUCTS - Kohinoor Jewelry Shop
# FILE: Kohinoor/backend/app/database/insert_product.py
# PURPOSE: 50 Oxidized products ko PostgreSQL + Pinecone mein insert karna
# ======================================================
 
import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
 
from dotenv import load_dotenv
from sqlalchemy.orm import sessionmaker
from connection import engine, SessionLocal
from models import Product
from pinecone import Pinecone
 
load_dotenv()
 
session = SessionLocal()
pc = Pinecone(api_key=os.getenv("PINECONE_API_KEY"))
index = pc.Index(os.getenv("PINECONE_INDEX"))
 
products = [
    # ─── EARRINGS (15 products) ───
    {
        "id": "prd_ox_001",
        "slug": "oxidized-silver-stud-earrings",
        "name": "Oxidized Silver Stud Earrings",
        "description": "Classic oxidized silver stud earrings with traditional design. Perfect for daily wear and festive occasions.",
        "short_description": "Classic oxidized silver studs",
        "price": 399.0,
        "original_price": 599.0,
        "discount": 33.0,
        "stock": 20,
        "rating": 4.5,
        "review_count": 85,
        "images": ["https://ik.imagekit.io/lrpk6giraj/SILVER%20OXIDISED%20STUDS%20EARRINGS%20only%20at_.jpg"],
        "category": "Earrings",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "1.5 cm",
        "gender": ["Women"],
        "occasions": ["Daily Wear", "Casual", "Festive"],
        "style_tags": ["Traditional", "Ethnic", "Minimal"],
        "tags": ["Earrings", "Studs", "Oxidized", "Silver"],
        "wear_type": "Ear",
        "embedding_text": "Classic oxidized silver stud earrings traditional ethnic minimal design for daily wear casual and festive occasions.",
        "related_products": ["prd_ox_002", "prd_ox_003"],
        "complete_look": ["prd_ox_010"],
        "featured": True,
        "is_new": True,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_002",
        "slug": "oxidized-jhumka-earrings-ethnic",
        "name": "Oxidized Jhumka Earrings",
        "description": "Stunning oxidized jhumka earrings with intricate ethnic design. A must-have for every ethnic wardrobe.",
        "short_description": "Ethnic oxidized jhumka earrings",
        "price": 499.0,
        "original_price": 799.0,
        "discount": 37.0,
        "stock": 18,
        "rating": 4.8,
        "review_count": 150,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Elevate%20your%20ethnic%20style%20with%20these%20stunning_.jpg"],
        "category": "Earrings",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "4 cm",
        "gender": ["Women"],
        "occasions": ["Festive", "Wedding", "Casual"],
        "style_tags": ["Traditional", "Ethnic", "Boho"],
        "tags": ["Earrings", "Jhumka", "Oxidized"],
        "wear_type": "Ear",
        "embedding_text": "Stunning oxidized jhumka earrings intricate ethnic boho design for festive wedding and casual occasions.",
        "related_products": ["prd_ox_001", "prd_ox_003"],
        "complete_look": ["prd_ox_010"],
        "featured": True,
        "is_new": True,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_003",
        "slug": "oxidized-chandbali-earrings",
        "name": "Oxidized Silver Chandbali Earrings",
        "description": "Traditional oxidized silver chandbali earrings with moon-shaped design. Perfect for ethnic and festive occasions.",
        "short_description": "Traditional chandbali earrings",
        "price": 599.0,
        "original_price": 899.0,
        "discount": 33.0,
        "stock": 15,
        "rating": 4.7,
        "review_count": 120,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Oxidised%20Silver%20Chandbali%20Earrings,%20Traditional_.jpg"],
        "category": "Earrings",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "5 cm",
        "gender": ["Women"],
        "occasions": ["Wedding", "Festive", "Party"],
        "style_tags": ["Traditional", "Royal", "Ethnic"],
        "tags": ["Earrings", "Chandbali", "Oxidized"],
        "wear_type": "Ear",
        "embedding_text": "Traditional oxidized silver chandbali moon shaped earrings royal ethnic style for wedding festive and party.",
        "related_products": ["prd_ox_001", "prd_ox_002"],
        "complete_look": ["prd_ox_010"],
        "featured": True,
        "is_new": False,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_004",
        "slug": "oxidized-tribal-earrings",
        "name": "Oxidized Tribal Drop Earrings",
        "description": "Bold oxidized tribal drop earrings with handcrafted design. Perfect for making a statement.",
        "short_description": "Bold tribal drop earrings",
        "price": 549.0,
        "original_price": 799.0,
        "discount": 31.0,
        "stock": 12,
        "rating": 4.6,
        "review_count": 95,
        "images": ["https://ik.imagekit.io/lrpk6giraj/597149231881043874.jpg"],
        "category": "Earrings",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "5.5 cm",
        "gender": ["Women"],
        "occasions": ["Festive", "Casual", "Party"],
        "style_tags": ["Tribal", "Boho", "Bold"],
        "tags": ["Earrings", "Tribal", "Oxidized", "Drop"],
        "wear_type": "Ear",
        "embedding_text": "Bold oxidized tribal drop earrings handcrafted boho style for festive casual and party occasions.",
        "related_products": ["prd_ox_002", "prd_ox_005"],
        "complete_look": ["prd_ox_011"],
        "featured": False,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_005",
        "slug": "oxidized-long-jhumka-earrings",
        "name": "Oxidized Long Jhumka Earrings",
        "description": "Elegant long oxidized jhumka earrings under budget. Lightweight and comfortable for all-day wear.",
        "short_description": "Long oxidized jhumka earrings",
        "price": 449.0,
        "original_price": 699.0,
        "discount": 35.0,
        "stock": 25,
        "rating": 4.7,
        "review_count": 130,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Looking%20for%20oxidised%20long%20jhumka%20earrings%20under_.jpg"],
        "category": "Earrings",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "6 cm",
        "gender": ["Women"],
        "occasions": ["Festive", "Wedding", "Casual"],
        "style_tags": ["Traditional", "Ethnic", "Elegant"],
        "tags": ["Earrings", "Jhumka", "Long", "Oxidized"],
        "wear_type": "Ear",
        "embedding_text": "Elegant long oxidized jhumka earrings lightweight comfortable traditional ethnic style for festive wedding occasions.",
        "related_products": ["prd_ox_002", "prd_ox_004"],
        "complete_look": ["prd_ox_010"],
        "featured": True,
        "is_new": True,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_006",
        "slug": "oxidized-afghani-ghungroo-earrings",
        "name": "Afghani Ghungroo Oxidized Earrings",
        "description": "Traditional Afghani ghungroo oxidized earrings with bell design. Unique and eye-catching ethnic style.",
        "short_description": "Afghani ghungroo earrings",
        "price": 649.0,
        "original_price": 999.0,
        "discount": 35.0,
        "stock": 10,
        "rating": 4.8,
        "review_count": 75,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Afghani%20Ghungroo%20Earrings%20with%20Ghungroo_.jpg"],
        "category": "Earrings",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "7 cm",
        "gender": ["Women"],
        "occasions": ["Festive", "Wedding", "Party"],
        "style_tags": ["Afghani", "Tribal", "Ethnic", "Bold"],
        "tags": ["Earrings", "Afghani", "Ghungroo", "Oxidized"],
        "wear_type": "Ear",
        "embedding_text": "Traditional Afghani ghungroo oxidized earrings bell design unique ethnic tribal style for festive wedding party.",
        "related_products": ["prd_ox_004", "prd_ox_005"],
        "complete_look": ["prd_ox_012"],
        "featured": True,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_007",
        "slug": "oxidized-silver-jhumka-beautiful",
        "name": "Beautiful Oxidized Silver Jhumka",
        "description": "Beautiful oxidized silver jhumka earrings with detailed craftsmanship. A timeless ethnic accessory.",
        "short_description": "Beautiful silver jhumka",
        "price": 529.0,
        "original_price": 799.0,
        "discount": 33.0,
        "stock": 20,
        "rating": 4.9,
        "review_count": 180,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Beautiful%20oxidised%20silver%20jhumka%20earrings_.jpg"],
        "category": "Earrings",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "4.5 cm",
        "gender": ["Women"],
        "occasions": ["Festive", "Wedding", "Daily Wear"],
        "style_tags": ["Traditional", "Ethnic", "Classic"],
        "tags": ["Earrings", "Jhumka", "Oxidized", "Silver"],
        "wear_type": "Ear",
        "embedding_text": "Beautiful oxidized silver jhumka earrings detailed craftsmanship timeless ethnic accessory for festive wedding daily wear.",
        "related_products": ["prd_ox_002", "prd_ox_005"],
        "complete_look": ["prd_ox_010"],
        "featured": True,
        "is_new": False,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_008",
        "slug": "oxidized-large-hoop-earrings",
        "name": "Oxidized Large Hoop Earrings",
        "description": "Stunning large oxidized hoop earrings with intricate pattern. Makes a bold ethnic statement.",
        "short_description": "Large oxidized hoop earrings",
        "price": 479.0,
        "original_price": 699.0,
        "discount": 31.0,
        "stock": 18,
        "rating": 4.6,
        "review_count": 90,
        "images": ["https://ik.imagekit.io/lrpk6giraj/4714774602427611.jpg"],
        "category": "Earrings",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "5 cm",
        "gender": ["Women"],
        "occasions": ["Casual", "Festive", "Party"],
        "style_tags": ["Boho", "Ethnic", "Bold"],
        "tags": ["Earrings", "Hoops", "Oxidized"],
        "wear_type": "Ear",
        "embedding_text": "Stunning large oxidized hoop earrings intricate pattern bold ethnic boho style for casual festive party.",
        "related_products": ["prd_ox_006", "prd_ox_007"],
        "complete_look": ["prd_ox_011"],
        "featured": False,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_009",
        "slug": "oxidized-bollywood-tribal-earrings",
        "name": "Bollywood Tribal Oxidized Earrings",
        "description": "Handmade Bollywood tribal oxidized silver plated earrings. Statement ethnic jewelry for special occasions.",
        "short_description": "Bollywood tribal oxidized earrings",
        "price": 699.0,
        "original_price": 999.0,
        "discount": 30.0,
        "stock": 8,
        "rating": 4.7,
        "review_count": 65,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Bollywood%20Tribal%20Oxidized%20Silver%20Plated%20Handmade_.jpg"],
        "category": "Earrings",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "6.5 cm",
        "gender": ["Women"],
        "occasions": ["Wedding", "Festive", "Party"],
        "style_tags": ["Bollywood", "Tribal", "Ethnic", "Statement"],
        "tags": ["Earrings", "Tribal", "Bollywood", "Oxidized"],
        "wear_type": "Ear",
        "embedding_text": "Handmade Bollywood tribal oxidized silver plated earrings statement ethnic jewelry for wedding festive party.",
        "related_products": ["prd_ox_006", "prd_ox_008"],
        "complete_look": ["prd_ox_012"],
        "featured": True,
        "is_new": False,
        "is_bestseller": True,
    },
 
    # ─── NECKLACES (10 products) ───
    {
        "id": "prd_ox_010",
        "slug": "oxidized-premium-mala-necklace",
        "name": "Premium Oxidized Indian Mala Necklace",
        "description": "Premium oxidized Indian mala necklace with traditional design. Limited stock available.",
        "short_description": "Premium oxidized mala necklace",
        "price": 899.0,
        "original_price": 1299.0,
        "discount": 30.0,
        "stock": 10,
        "rating": 4.8,
        "review_count": 110,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Premium%20Indian%20Oxidised%20Mala%20Very%20limited%20in_.jpg"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "22 inch",
        "gender": ["Women"],
        "occasions": ["Wedding", "Festive", "Party"],
        "style_tags": ["Traditional", "Royal", "Ethnic"],
        "tags": ["Necklace", "Mala", "Oxidized", "Indian"],
        "wear_type": "Neck",
        "embedding_text": "Premium oxidized Indian mala necklace traditional royal ethnic design for wedding festive party occasions.",
        "related_products": ["prd_ox_011", "prd_ox_012"],
        "complete_look": ["prd_ox_002"],
        "featured": True,
        "is_new": True,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_011",
        "slug": "oxidized-choker-necklace",
        "name": "Beautiful Oxidized Choker Necklace",
        "description": "Beautiful oxidized choker necklace paired with traditional design. A stunning ethnic accessory.",
        "short_description": "Oxidized choker necklace",
        "price": 799.0,
        "original_price": 1199.0,
        "discount": 33.0,
        "stock": 12,
        "rating": 4.7,
        "review_count": 95,
        "images": ["https://ik.imagekit.io/lrpk6giraj/beautiful%20oxidised%20choker%20necklace%20paired%20with_.jpg"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "14 inch",
        "gender": ["Women"],
        "occasions": ["Wedding", "Festive", "Party"],
        "style_tags": ["Traditional", "Ethnic", "Bold"],
        "tags": ["Necklace", "Choker", "Oxidized"],
        "wear_type": "Neck",
        "embedding_text": "Beautiful oxidized choker necklace traditional ethnic bold style for wedding festive party.",
        "related_products": ["prd_ox_010", "prd_ox_012"],
        "complete_look": ["prd_ox_003"],
        "featured": True,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_012",
        "slug": "oxidized-kolhapur-necklace",
        "name": "Oxidized Kolhapur Style Necklace",
        "description": "Timeless charm of Kolhapur in oxidized silver necklace. Traditional Maharashtrian ethnic jewelry.",
        "short_description": "Kolhapur style oxidized necklace",
        "price": 999.0,
        "original_price": 1499.0,
        "discount": 33.0,
        "stock": 8,
        "rating": 4.9,
        "review_count": 140,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Unleash%20the%20timeless%20charm%20of%20Kolhapur!%20_%20This_.jpg"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "18 inch",
        "gender": ["Women"],
        "occasions": ["Wedding", "Festive", "Traditional"],
        "style_tags": ["Traditional", "Kolhapuri", "Royal", "Ethnic"],
        "tags": ["Necklace", "Kolhapur", "Oxidized", "Traditional"],
        "wear_type": "Neck",
        "embedding_text": "Timeless Kolhapur style oxidized silver necklace traditional Maharashtrian ethnic jewelry for wedding festive occasions.",
        "related_products": ["prd_ox_010", "prd_ox_011"],
        "complete_look": ["prd_ox_006"],
        "featured": True,
        "is_new": False,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_013",
        "slug": "oxidized-anti-tarnish-necklace",
        "name": "Oxidized Anti Tarnish Necklace",
        "description": "Premium oxidized anti tarnish necklace with limited stock. Durable and long-lasting ethnic jewelry.",
        "short_description": "Anti tarnish oxidized necklace",
        "price": 849.0,
        "original_price": 1199.0,
        "discount": 29.0,
        "stock": 15,
        "rating": 4.7,
        "review_count": 85,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Anti%20tarnish%20Nacklace%20%E2%9D%A4%EF%B8%8F%20Limited%20Stock%20left_._DM_"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver", "Anti Tarnish"],
        "gemstones": [],
        "dimensions": "18 inch",
        "gender": ["Women"],
        "occasions": ["Daily Wear", "Festive", "Casual"],
        "style_tags": ["Traditional", "Ethnic", "Durable"],
        "tags": ["Necklace", "Anti Tarnish", "Oxidized"],
        "wear_type": "Neck",
        "embedding_text": "Premium oxidized anti tarnish necklace durable long lasting ethnic jewelry for daily wear festive casual.",
        "related_products": ["prd_ox_011", "prd_ox_014"],
        "complete_look": ["prd_ox_001"],
        "featured": False,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_014",
        "slug": "oxidized-bold-statement-necklace",
        "name": "Oxidized Bold Statement Necklace",
        "description": "Make a bold traditional statement with this oxidized silver necklace. Perfect for ethnic occasions.",
        "short_description": "Bold oxidized statement necklace",
        "price": 1099.0,
        "original_price": 1599.0,
        "discount": 31.0,
        "stock": 10,
        "rating": 4.8,
        "review_count": 75,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Make%20a%20bold%20traditional%20statement%20with%20this_.jpg"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "20 inch",
        "gender": ["Women"],
        "occasions": ["Wedding", "Festive", "Party"],
        "style_tags": ["Bold", "Statement", "Traditional", "Ethnic"],
        "tags": ["Necklace", "Statement", "Oxidized"],
        "wear_type": "Neck",
        "embedding_text": "Bold traditional statement oxidized silver necklace ethnic style for wedding festive party occasions.",
        "related_products": ["prd_ox_012", "prd_ox_013"],
        "complete_look": ["prd_ox_009"],
        "featured": True,
        "is_new": True,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_015",
        "slug": "oxidized-rustic-charm-necklace",
        "name": "Oxidized Rustic Charm Necklace",
        "description": "Oxidized jewelry known for its rustic charm and ethnic appeal. A classic piece for ethnic wardrobe.",
        "short_description": "Rustic charm oxidized necklace",
        "price": 749.0,
        "original_price": 1099.0,
        "discount": 31.0,
        "stock": 14,
        "rating": 4.6,
        "review_count": 88,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Oxidized%20jewellery%20is%20known%20for%20its%20rustic%20charm_.jpg"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "18 inch",
        "gender": ["Women"],
        "occasions": ["Casual", "Festive", "Daily Wear"],
        "style_tags": ["Rustic", "Ethnic", "Classic"],
        "tags": ["Necklace", "Rustic", "Oxidized"],
        "wear_type": "Neck",
        "embedding_text": "Oxidized rustic charm necklace ethnic appeal classic piece for casual festive daily wear.",
        "related_products": ["prd_ox_013", "prd_ox_014"],
        "complete_look": ["prd_ox_007"],
        "featured": False,
        "is_new": False,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_016",
        "slug": "oxidized-tribal-silver-necklace",
        "name": "Oxidized Tribal Silver Necklace",
        "description": "Rare oxidized tribal silver necklace with ethnic design. Limited stock available.",
        "short_description": "Tribal oxidized silver necklace",
        "price": 1199.0,
        "original_price": 1699.0,
        "discount": 29.0,
        "stock": 6,
        "rating": 4.9,
        "review_count": 55,
        "images": ["https://ik.imagekit.io/lrpk6giraj/_%20Rare%20artificial%20jewellery%20deal%20!%20Comment%20_Power__.jpg"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "22 inch",
        "gender": ["Women"],
        "occasions": ["Wedding", "Festive", "Party"],
        "style_tags": ["Tribal", "Ethnic", "Rare", "Bold"],
        "tags": ["Necklace", "Tribal", "Oxidized", "Rare"],
        "wear_type": "Neck",
        "embedding_text": "Rare oxidized tribal silver necklace ethnic design limited stock for wedding festive party.",
        "related_products": ["prd_ox_014", "prd_ox_015"],
        "complete_look": ["prd_ox_009"],
        "featured": True,
        "is_new": True,
        "is_bestseller": False,
    },
 
    # ─── BANGLES (9 products) ───
    {
        "id": "prd_ox_017",
        "slug": "oxidized-silver-bangle-set",
        "name": "Oxidized Silver Bangle Set",
        "description": "Samridhi DC oxidized silver alloy bangle set. Traditional design with modern craftsmanship.",
        "short_description": "Oxidized silver bangle set",
        "price": 699.0,
        "original_price": 999.0,
        "discount": 30.0,
        "stock": 20,
        "rating": 4.6,
        "review_count": 105,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Samridhi%20DC%20Metal,%20Oxidised%20Silver,%20Alloy%20Bangle%20Price%20in%20India%20-%20Buy%20Samridhi%20DC%20Metal,%20Oxidised%20Silver,%20Alloy%20Bangle%20Online%20at%20Best%20Prices%20in%20India%20_%20Flipkart_com.jpg"],
        "category": "Bangle",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver", "Alloy"],
        "gemstones": [],
        "dimensions": "2.6 size",
        "gender": ["Women"],
        "occasions": ["Festive", "Wedding", "Daily Wear"],
        "style_tags": ["Traditional", "Ethnic", "Classic"],
        "tags": ["Bangle", "Oxidized", "Silver", "Set"],
        "wear_type": "Wrist",
        "embedding_text": "Oxidized silver alloy bangle set traditional ethnic classic design for festive wedding daily wear.",
        "related_products": ["prd_ox_018", "prd_ox_019"],
        "complete_look": ["prd_ox_010"],
        "featured": True,
        "is_new": False,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_018",
        "slug": "oxidized-two-piece-bangle-set",
        "name": "Oxidized Two Piece Bangle Set",
        "description": "Elegant set of two oxidized bangles with traditional design. Perfect pair for ethnic occasions.",
        "short_description": "Two piece oxidized bangle set",
        "price": 599.0,
        "original_price": 899.0,
        "discount": 33.0,
        "stock": 18,
        "rating": 4.5,
        "review_count": 88,
        "images": ["https://ik.imagekit.io/lrpk6giraj/A%20set%20of%20bangles%20consisting%20of%20two%20pieces_.jpg"],
        "category": "Bangle",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "2.6 size",
        "gender": ["Women"],
        "occasions": ["Festive", "Casual", "Wedding"],
        "style_tags": ["Traditional", "Ethnic", "Minimal"],
        "tags": ["Bangle", "Oxidized", "Set"],
        "wear_type": "Wrist",
        "embedding_text": "Elegant two piece oxidized bangle set traditional ethnic minimal design for festive casual wedding.",
        "related_products": ["prd_ox_017", "prd_ox_019"],
        "complete_look": ["prd_ox_011"],
        "featured": False,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_019",
        "slug": "oxidized-necklace-bangle-set",
        "name": "Oxidized Necklace and Bangle Set",
        "description": "Complete oxidized set with openable bangles and necklace. A perfect ethnic jewelry combo.",
        "short_description": "Oxidized necklace bangle combo",
        "price": 1299.0,
        "original_price": 1899.0,
        "discount": 31.0,
        "stock": 10,
        "rating": 4.8,
        "review_count": 70,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Oxidised%20set%20comes%20with%20openable%20bangles%20%C2%A0necklace_.jpg"],
        "category": "Bangle",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "2.6 size",
        "gender": ["Women"],
        "occasions": ["Wedding", "Festive", "Party"],
        "style_tags": ["Traditional", "Ethnic", "Combo", "Royal"],
        "tags": ["Bangle", "Necklace", "Set", "Oxidized"],
        "wear_type": "Wrist",
        "embedding_text": "Complete oxidized set openable bangles necklace combo ethnic royal style for wedding festive party.",
        "related_products": ["prd_ox_017", "prd_ox_018"],
        "complete_look": ["prd_ox_012"],
        "featured": True,
        "is_new": True,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_020",
        "slug": "oxidized-designer-brass-bangle",
        "name": "Oxidized Designer Brass Bangle",
        "description": "Oxidized designer brass bangle with ethnic pattern. Unique handcrafted piece for ethnic wardrobe.",
        "short_description": "Designer oxidized brass bangle",
        "price": 749.0,
        "original_price": 1099.0,
        "discount": 31.0,
        "stock": 12,
        "rating": 4.6,
        "review_count": 60,
        "images": ["https://ik.imagekit.io/lrpk6giraj/_%20WhatsApp%20number%20-%209990050848%20_%20DM%20for%20order_.jpg"],
        "category": "Bangle",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Brass"],
        "gemstones": [],
        "dimensions": "2.4 size",
        "gender": ["Women"],
        "occasions": ["Festive", "Casual", "Daily Wear"],
        "style_tags": ["Designer", "Ethnic", "Handcrafted"],
        "tags": ["Bangle", "Brass", "Oxidized", "Designer"],
        "wear_type": "Wrist",
        "embedding_text": "Designer oxidized brass bangle ethnic pattern handcrafted unique piece for festive casual daily wear.",
        "related_products": ["prd_ox_018", "prd_ox_019"],
        "complete_look": ["prd_ox_015"],
        "featured": False,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_021",
        "slug": "oxidized-limited-stock-bangle",
        "name": "Oxidized Silver Bangle Limited Stock",
        "description": "Grab this oxidized silver bangle before stock runs out. Traditional ethnic design with premium finish.",
        "short_description": "Limited stock oxidized bangle",
        "price": 649.0,
        "original_price": 949.0,
        "discount": 31.0,
        "stock": 5,
        "rating": 4.7,
        "review_count": 45,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Limited%20stock%20!%20Grab%20yours%20ASAP%20before%20they%20are_.jpg"],
        "category": "Bangle",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "2.6 size",
        "gender": ["Women"],
        "occasions": ["Festive", "Wedding"],
        "style_tags": ["Traditional", "Ethnic", "Premium"],
        "tags": ["Bangle", "Oxidized", "Limited"],
        "wear_type": "Wrist",
        "embedding_text": "Limited stock oxidized silver bangle traditional ethnic premium finish for festive wedding occasions.",
        "related_products": ["prd_ox_019", "prd_ox_020"],
        "complete_look": ["prd_ox_014"],
        "featured": True,
        "is_new": False,
        "is_bestseller": True,
    },
 
    # ─── RINGS (8 products) ───
    {
        "id": "prd_ox_022",
        "slug": "oxidized-designer-brass-ring",
        "name": "Designer Oxidized Brass Ring",
        "description": "Designer oxidized brass ring with ethnic pattern. Unique handcrafted piece by Namanarts.",
        "short_description": "Designer oxidized brass ring",
        "price": 349.0,
        "original_price": 499.0,
        "discount": 30.0,
        "stock": 25,
        "rating": 4.5,
        "review_count": 70,
        "images": ["https://ik.imagekit.io/lrpk6giraj/DESIGNER%20OXIDISED%20BRASS%20RING%20only%20at%20@namanarts_in_.jpg"],
        "category": "Ring",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Brass"],
        "gemstones": [],
        "dimensions": "Size 17",
        "gender": ["Women"],
        "occasions": ["Casual", "Daily Wear", "Festive"],
        "style_tags": ["Designer", "Ethnic", "Handcrafted"],
        "tags": ["Ring", "Brass", "Oxidized", "Designer"],
        "wear_type": "Finger",
        "embedding_text": "Designer oxidized brass ring ethnic pattern handcrafted unique piece for casual daily wear festive.",
        "related_products": ["prd_ox_023", "prd_ox_024"],
        "complete_look": ["prd_ox_001"],
        "featured": True,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_023",
        "slug": "oxidized-silver-ethnic-ring",
        "name": "Oxidized Silver Ethnic Ring",
        "description": "Traditional oxidized silver ethnic ring with detailed craftsmanship. Perfect for ethnic occasions.",
        "short_description": "Oxidized silver ethnic ring",
        "price": 299.0,
        "original_price": 449.0,
        "discount": 33.0,
        "stock": 30,
        "rating": 4.4,
        "review_count": 95,
        "images": ["https://ik.imagekit.io/lrpk6giraj/618963542553314693.jpg"],
        "category": "Ring",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "Size 16",
        "gender": ["Women"],
        "occasions": ["Daily Wear", "Casual", "Festive"],
        "style_tags": ["Traditional", "Ethnic", "Classic"],
        "tags": ["Ring", "Silver", "Oxidized", "Ethnic"],
        "wear_type": "Finger",
        "embedding_text": "Traditional oxidized silver ethnic ring detailed craftsmanship classic style for daily wear casual festive.",
        "related_products": ["prd_ox_022", "prd_ox_024"],
        "complete_look": ["prd_ox_002"],
        "featured": False,
        "is_new": True,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_024",
        "slug": "oxidized-tribal-ring",
        "name": "Oxidized Tribal Statement Ring",
        "description": "Bold oxidized tribal statement ring with handcrafted design. Makes a strong ethnic statement.",
        "short_description": "Tribal oxidized statement ring",
        "price": 399.0,
        "original_price": 599.0,
        "discount": 33.0,
        "stock": 20,
        "rating": 4.6,
        "review_count": 60,
        "images": ["https://ik.imagekit.io/lrpk6giraj/332562753743330773.jpg"],
        "category": "Ring",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "Size 17",
        "gender": ["Women"],
        "occasions": ["Festive", "Party", "Casual"],
        "style_tags": ["Tribal", "Bold", "Ethnic", "Statement"],
        "tags": ["Ring", "Tribal", "Oxidized", "Statement"],
        "wear_type": "Finger",
        "embedding_text": "Bold oxidized tribal statement ring handcrafted ethnic design for festive party casual occasions.",
        "related_products": ["prd_ox_022", "prd_ox_023"],
        "complete_look": ["prd_ox_004"],
        "featured": True,
        "is_new": False,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_025",
        "slug": "oxidized-floral-ring",
        "name": "Oxidized Floral Design Ring",
        "description": "Elegant oxidized floral design ring with traditional motifs. A beautiful ethnic accessory.",
        "short_description": "Oxidized floral ring",
        "price": 349.0,
        "original_price": 499.0,
        "discount": 30.0,
        "stock": 22,
        "rating": 4.5,
        "review_count": 75,
        "images": ["https://ik.imagekit.io/lrpk6giraj/485403666111634906.jpg"],
        "category": "Ring",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "Size 16",
        "gender": ["Women"],
        "occasions": ["Casual", "Festive", "Daily Wear"],
        "style_tags": ["Floral", "Ethnic", "Elegant"],
        "tags": ["Ring", "Floral", "Oxidized"],
        "wear_type": "Finger",
        "embedding_text": "Elegant oxidized floral design ring traditional motifs ethnic accessory for casual festive daily wear.",
        "related_products": ["prd_ox_023", "prd_ox_024"],
        "complete_look": ["prd_ox_007"],
        "featured": False,
        "is_new": True,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_026",
        "slug": "oxidized-adjustable-ring",
        "name": "Oxidized Adjustable Silver Ring",
        "description": "Oxidized adjustable silver ring with ethnic design. One size fits all with comfortable wear.",
        "short_description": "Adjustable oxidized silver ring",
        "price": 279.0,
        "original_price": 399.0,
        "discount": 30.0,
        "stock": 35,
        "rating": 4.4,
        "review_count": 110,
        "images": ["https://ik.imagekit.io/lrpk6giraj/292030357099537261.jpg"],
        "category": "Ring",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "Adjustable",
        "gender": ["Women"],
        "occasions": ["Daily Wear", "Casual"],
        "style_tags": ["Minimal", "Ethnic", "Comfortable"],
        "tags": ["Ring", "Adjustable", "Oxidized"],
        "wear_type": "Finger",
        "embedding_text": "Oxidized adjustable silver ring ethnic design comfortable daily wear casual one size fits all.",
        "related_products": ["prd_ox_022", "prd_ox_025"],
        "complete_look": ["prd_ox_001"],
        "featured": False,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_027",
        "slug": "oxidized-peacock-ring",
        "name": "Oxidized Peacock Design Ring",
        "description": "Beautiful oxidized peacock design ring with intricate detailing. A statement ethnic piece.",
        "short_description": "Oxidized peacock ring",
        "price": 429.0,
        "original_price": 629.0,
        "discount": 31.0,
        "stock": 15,
        "rating": 4.7,
        "review_count": 55,
        "images": ["https://ik.imagekit.io/lrpk6giraj/209487820161858162.jpg"],
        "category": "Ring",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "Size 17",
        "gender": ["Women"],
        "occasions": ["Festive", "Wedding", "Party"],
        "style_tags": ["Peacock", "Ethnic", "Statement", "Royal"],
        "tags": ["Ring", "Peacock", "Oxidized"],
        "wear_type": "Finger",
        "embedding_text": "Beautiful oxidized peacock design ring intricate detailing statement ethnic royal piece for festive wedding party.",
        "related_products": ["prd_ox_024", "prd_ox_026"],
        "complete_look": ["prd_ox_012"],
        "featured": True,
        "is_new": True,
        "is_bestseller": False,
    },
 
    # ─── PENDANTS (8 products) ───
    {
        "id": "prd_ox_028",
        "slug": "oxidized-goddess-pendant",
        "name": "Oxidized Goddess Pendant Necklace",
        "description": "Spiritual oxidized goddess pendant with traditional design. A meaningful ethnic accessory.",
        "short_description": "Oxidized goddess pendant",
        "price": 649.0,
        "original_price": 949.0,
        "discount": 31.0,
        "stock": 12,
        "rating": 4.8,
        "review_count": 80,
        "images": ["https://ik.imagekit.io/lrpk6giraj/26529085300793173.jpg"],
        "category": "Pendant",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "18 inch chain",
        "gender": ["Women"],
        "occasions": ["Religious", "Festive", "Daily Wear"],
        "style_tags": ["Spiritual", "Traditional", "Ethnic"],
        "tags": ["Pendant", "Goddess", "Oxidized", "Spiritual"],
        "wear_type": "Neck",
        "embedding_text": "Spiritual oxidized goddess pendant traditional ethnic meaningful accessory for religious festive daily wear.",
        "related_products": ["prd_ox_029", "prd_ox_030"],
        "complete_look": ["prd_ox_010"],
        "featured": True,
        "is_new": False,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_029",
        "slug": "oxidized-tribal-pendant",
        "name": "Oxidized Tribal Pendant",
        "description": "Bold oxidized tribal pendant with ethnic design. A unique statement piece for ethnic wardrobe.",
        "short_description": "Tribal oxidized pendant",
        "price": 549.0,
        "original_price": 799.0,
        "discount": 31.0,
        "stock": 15,
        "rating": 4.6,
        "review_count": 65,
        "images": ["https://ik.imagekit.io/lrpk6giraj/128071183149611312.jpg"],
        "category": "Pendant",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "20 inch chain",
        "gender": ["Women"],
        "occasions": ["Festive", "Casual", "Party"],
        "style_tags": ["Tribal", "Ethnic", "Bold"],
        "tags": ["Pendant", "Tribal", "Oxidized"],
        "wear_type": "Neck",
        "embedding_text": "Bold oxidized tribal pendant ethnic design unique statement piece for festive casual party.",
        "related_products": ["prd_ox_028", "prd_ox_030"],
        "complete_look": ["prd_ox_004"],
        "featured": False,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_030",
        "slug": "oxidized-nature-pendant",
        "name": "Oxidized Nature Symbol Pendant",
        "description": "Celebrate nature and symbolism with this oxidized pendant. Elegant ethnic design with natural motifs.",
        "short_description": "Nature symbol oxidized pendant",
        "price": 599.0,
        "original_price": 899.0,
        "discount": 33.0,
        "stock": 14,
        "rating": 4.7,
        "review_count": 50,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Feiern%20Sie%20die%20Natur%20und%20Symbolik%20mit%20dieser_.jpg"],
        "category": "Pendant",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "18 inch chain",
        "gender": ["Women"],
        "occasions": ["Casual", "Daily Wear", "Festive"],
        "style_tags": ["Nature", "Ethnic", "Elegant", "Symbolic"],
        "tags": ["Pendant", "Nature", "Oxidized"],
        "wear_type": "Neck",
        "embedding_text": "Oxidized nature symbol pendant elegant ethnic natural motifs design for casual daily wear festive.",
        "related_products": ["prd_ox_028", "prd_ox_029"],
        "complete_look": ["prd_ox_015"],
        "featured": True,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_031",
        "slug": "oxidized-ethnic-moon-pendant",
        "name": "Oxidized Ethnic Moon Pendant",
        "description": "Beautiful oxidized ethnic moon pendant with traditional design. A must-have for ethnic jewelry lovers.",
        "short_description": "Ethnic moon oxidized pendant",
        "price": 499.0,
        "original_price": 749.0,
        "discount": 33.0,
        "stock": 18,
        "rating": 4.5,
        "review_count": 72,
        "images": ["https://ik.imagekit.io/lrpk6giraj/236790892900808893.jpg"],
        "category": "Pendant",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "18 inch chain",
        "gender": ["Women"],
        "occasions": ["Casual", "Festive", "Daily Wear"],
        "style_tags": ["Ethnic", "Minimal", "Classic"],
        "tags": ["Pendant", "Moon", "Oxidized"],
        "wear_type": "Neck",
        "embedding_text": "Beautiful oxidized ethnic moon pendant traditional minimal classic design for casual festive daily wear.",
        "related_products": ["prd_ox_029", "prd_ox_030"],
        "complete_look": ["prd_ox_008"],
        "featured": False,
        "is_new": True,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_032",
        "slug": "oxidized-floral-pendant",
        "name": "Oxidized Floral Pendant",
        "description": "Elegant oxidized floral pendant with intricate design. Perfect for ethnic and casual occasions.",
        "short_description": "Oxidized floral pendant",
        "price": 529.0,
        "original_price": 799.0,
        "discount": 33.0,
        "stock": 16,
        "rating": 4.6,
        "review_count": 58,
        "images": ["https://ik.imagekit.io/lrpk6giraj/703265298107893485.jpg"],
        "category": "Pendant",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "18 inch chain",
        "gender": ["Women"],
        "occasions": ["Casual", "Festive"],
        "style_tags": ["Floral", "Ethnic", "Elegant"],
        "tags": ["Pendant", "Floral", "Oxidized"],
        "wear_type": "Neck",
        "embedding_text": "Elegant oxidized floral pendant intricate design ethnic casual festive occasions.",
        "related_products": ["prd_ox_030", "prd_ox_031"],
        "complete_look": ["prd_ox_005"],
        "featured": True,
        "is_new": True,
        "is_bestseller": False,
    },
 
    # ─── BRACELETS (8 products) ───
    {
        "id": "prd_ox_033",
        "slug": "oxidized-silver-bracelet",
        "name": "Oxidized Silver Bracelet",
        "description": "Classic oxidized silver bracelet with traditional ethnic design. Perfect for daily wear.",
        "short_description": "Classic oxidized silver bracelet",
        "price": 549.0,
        "original_price": 799.0,
        "discount": 31.0,
        "stock": 20,
        "rating": 4.5,
        "review_count": 90,
        "images": ["https://ik.imagekit.io/lrpk6giraj/92957179804422027.jpg"],
        "category": "Bracelet",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "7 inch",
        "gender": ["Women"],
        "occasions": ["Daily Wear", "Casual", "Festive"],
        "style_tags": ["Traditional", "Ethnic", "Classic"],
        "tags": ["Bracelet", "Silver", "Oxidized"],
        "wear_type": "Wrist",
        "embedding_text": "Classic oxidized silver bracelet traditional ethnic design for daily wear casual festive occasions.",
        "related_products": ["prd_ox_034", "prd_ox_035"],
        "complete_look": ["prd_ox_010"],
        "featured": True,
        "is_new": False,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_034",
        "slug": "oxidized-tribal-bracelet",
        "name": "Oxidized Tribal Bracelet",
        "description": "Bold oxidized tribal bracelet with ethnic pattern. A statement piece for festive occasions.",
        "short_description": "Tribal oxidized bracelet",
        "price": 649.0,
        "original_price": 949.0,
        "discount": 31.0,
        "stock": 15,
        "rating": 4.6,
        "review_count": 70,
        "images": ["https://ik.imagekit.io/lrpk6giraj/483011128805724284.jpg"],
        "category": "Bracelet",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "7 inch",
        "gender": ["Women"],
        "occasions": ["Festive", "Party", "Casual"],
        "style_tags": ["Tribal", "Bold", "Ethnic"],
        "tags": ["Bracelet", "Tribal", "Oxidized"],
        "wear_type": "Wrist",
        "embedding_text": "Bold oxidized tribal bracelet ethnic pattern statement piece for festive party casual occasions.",
        "related_products": ["prd_ox_033", "prd_ox_035"],
        "complete_look": ["prd_ox_009"],
        "featured": False,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_035",
        "slug": "oxidized-cuff-bracelet",
        "name": "Oxidized Silver Cuff Bracelet",
        "description": "Stunning oxidized silver cuff bracelet with traditional design. Wide cuff with ethnic motifs.",
        "short_description": "Oxidized silver cuff bracelet",
        "price": 749.0,
        "original_price": 1099.0,
        "discount": 31.0,
        "stock": 12,
        "rating": 4.7,
        "review_count": 65,
        "images": ["https://ik.imagekit.io/lrpk6giraj/63261569762461590.jpg"],
        "category": "Bracelet",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "7 inch",
        "gender": ["Women"],
        "occasions": ["Festive", "Wedding", "Party"],
        "style_tags": ["Traditional", "Ethnic", "Statement"],
        "tags": ["Bracelet", "Cuff", "Oxidized"],
        "wear_type": "Wrist",
        "embedding_text": "Stunning oxidized silver cuff bracelet traditional ethnic motifs statement piece for festive wedding party.",
        "related_products": ["prd_ox_033", "prd_ox_034"],
        "complete_look": ["prd_ox_014"],
        "featured": True,
        "is_new": True,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_036",
        "slug": "oxidized-charm-bracelet",
        "name": "Oxidized Charm Bracelet",
        "description": "Delicate oxidized charm bracelet with ethnic motifs. Lightweight and perfect for daily wear.",
        "short_description": "Oxidized charm bracelet",
        "price": 499.0,
        "original_price": 749.0,
        "discount": 33.0,
        "stock": 18,
        "rating": 4.5,
        "review_count": 85,
        "images": ["https://ik.imagekit.io/lrpk6giraj/138626494776058504.jpg"],
        "category": "Bracelet",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "7 inch",
        "gender": ["Women"],
        "occasions": ["Daily Wear", "Casual", "Festive"],
        "style_tags": ["Minimal", "Ethnic", "Delicate"],
        "tags": ["Bracelet", "Charm", "Oxidized"],
        "wear_type": "Wrist",
        "embedding_text": "Delicate oxidized charm bracelet ethnic motifs lightweight minimal for daily wear casual festive.",
        "related_products": ["prd_ox_033", "prd_ox_035"],
        "complete_look": ["prd_ox_001"],
        "featured": False,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_037",
        "slug": "oxidized-bangle-bracelet",
        "name": "Oxidized Bangle Style Bracelet",
        "description": "Traditional oxidized bangle style bracelet with geometric pattern. Ethnic design for special occasions.",
        "short_description": "Oxidized bangle bracelet",
        "price": 599.0,
        "original_price": 899.0,
        "discount": 33.0,
        "stock": 16,
        "rating": 4.6,
        "review_count": 55,
        "images": ["https://ik.imagekit.io/lrpk6giraj/910571619579968395.jpg"],
        "category": "Bracelet",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "7 inch",
        "gender": ["Women"],
        "occasions": ["Festive", "Wedding", "Casual"],
        "style_tags": ["Traditional", "Geometric", "Ethnic"],
        "tags": ["Bracelet", "Bangle", "Oxidized"],
        "wear_type": "Wrist",
        "embedding_text": "Traditional oxidized bangle style bracelet geometric pattern ethnic design for festive wedding casual.",
        "related_products": ["prd_ox_034", "prd_ox_036"],
        "complete_look": ["prd_ox_011"],
        "featured": True,
        "is_new": False,
        "is_bestseller": True,
    },
 
    # ─── SETS / COMBOS (8 products) ───
    {
        "id": "prd_ox_038",
        "slug": "oxidized-jewelry-set-complete",
        "name": "Complete Oxidized Jewelry Set",
        "description": "Oxidized jewelry set with earrings and necklace. A complete ethnic look for festive occasions.",
        "short_description": "Complete oxidized jewelry set",
        "price": 1299.0,
        "original_price": 1899.0,
        "discount": 31.0,
        "stock": 8,
        "rating": 4.8,
        "review_count": 95,
        "images": ["https://ik.imagekit.io/lrpk6giraj/878764946057751244.jpg"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "18 inch",
        "gender": ["Women"],
        "occasions": ["Wedding", "Festive", "Party"],
        "style_tags": ["Traditional", "Ethnic", "Royal", "Complete Look"],
        "tags": ["Set", "Necklace", "Earrings", "Oxidized"],
        "wear_type": "Neck",
        "embedding_text": "Complete oxidized jewelry set earrings necklace traditional ethnic royal look for wedding festive party.",
        "related_products": ["prd_ox_010", "prd_ox_019"],
        "complete_look": ["prd_ox_002"],
        "featured": True,
        "is_new": True,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_039",
        "slug": "oxidized-necklace-earring-combo",
        "name": "Oxidized Necklace Earring Combo",
        "description": "Matching oxidized necklace and earring combo set. Perfect ethnic jewelry for wedding and festive.",
        "short_description": "Oxidized necklace earring combo",
        "price": 1199.0,
        "original_price": 1699.0,
        "discount": 29.0,
        "stock": 10,
        "rating": 4.7,
        "review_count": 80,
        "images": ["https://ik.imagekit.io/lrpk6giraj/617063586484321679.jpg"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "18 inch",
        "gender": ["Women"],
        "occasions": ["Wedding", "Festive"],
        "style_tags": ["Traditional", "Ethnic", "Matching"],
        "tags": ["Set", "Necklace", "Earrings", "Oxidized", "Combo"],
        "wear_type": "Neck",
        "embedding_text": "Matching oxidized necklace earring combo perfect ethnic jewelry for wedding festive occasions.",
        "related_products": ["prd_ox_038", "prd_ox_010"],
        "complete_look": ["prd_ox_003"],
        "featured": True,
        "is_new": False,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_040",
        "slug": "oxidized-full-bridal-set",
        "name": "Oxidized Full Bridal Set",
        "description": "Exquisite oxidized full bridal set with necklace, earrings and bangles. Complete ethnic bridal look.",
        "short_description": "Oxidized full bridal set",
        "price": 1899.0,
        "original_price": 2699.0,
        "discount": 29.0,
        "stock": 6,
        "rating": 4.9,
        "review_count": 120,
        "images": ["https://ik.imagekit.io/lrpk6giraj/This%20elegant%20and%20classy%20design%20This%20exquisite_.jpg"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "18 inch",
        "gender": ["Women"],
        "occasions": ["Wedding", "Festive", "Engagement"],
        "style_tags": ["Bridal", "Royal", "Ethnic", "Traditional"],
        "tags": ["Set", "Bridal", "Oxidized", "Full Set"],
        "wear_type": "Neck",
        "embedding_text": "Exquisite oxidized full bridal set necklace earrings bangles complete ethnic bridal look for wedding engagement.",
        "related_products": ["prd_ox_038", "prd_ox_039"],
        "complete_look": ["prd_ox_006"],
        "featured": True,
        "is_new": True,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_041",
        "slug": "oxidized-ethnic-maang-tikka-set",
        "name": "Oxidized Ethnic Jewelry Set with Tikka",
        "description": "Traditional oxidized ethnic jewelry set with maang tikka and earrings. Perfect for bridal occasions.",
        "short_description": "Oxidized jewelry set with tikka",
        "price": 1499.0,
        "original_price": 2199.0,
        "discount": 31.0,
        "stock": 8,
        "rating": 4.8,
        "review_count": 65,
        "images": ["https://ik.imagekit.io/lrpk6giraj/115967759147895983.jpg"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "18 inch",
        "gender": ["Women"],
        "occasions": ["Wedding", "Festive", "Engagement"],
        "style_tags": ["Bridal", "Traditional", "Ethnic", "Royal"],
        "tags": ["Set", "Tikka", "Oxidized", "Bridal"],
        "wear_type": "Neck",
        "embedding_text": "Traditional oxidized ethnic jewelry set maang tikka earrings bridal royal style for wedding engagement festive.",
        "related_products": ["prd_ox_040", "prd_ox_039"],
        "complete_look": ["prd_ox_009"],
        "featured": True,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_042",
        "slug": "oxidized-layered-necklace-set",
        "name": "Oxidized Layered Necklace Set",
        "description": "Beautiful layered oxidized necklace set with ethnic design. Makes a bold ethnic fashion statement.",
        "short_description": "Layered oxidized necklace set",
        "price": 1099.0,
        "original_price": 1599.0,
        "discount": 31.0,
        "stock": 10,
        "rating": 4.7,
        "review_count": 88,
        "images": ["https://ik.imagekit.io/lrpk6giraj/570690584036321496.jpg"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "18-22 inch",
        "gender": ["Women"],
        "occasions": ["Festive", "Party", "Wedding"],
        "style_tags": ["Layered", "Bold", "Ethnic", "Statement"],
        "tags": ["Necklace", "Layered", "Oxidized", "Set"],
        "wear_type": "Neck",
        "embedding_text": "Beautiful layered oxidized necklace set ethnic bold fashion statement for festive party wedding.",
        "related_products": ["prd_ox_038", "prd_ox_041"],
        "complete_look": ["prd_ox_008"],
        "featured": False,
        "is_new": True,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_043",
        "slug": "oxidized-anklet-set",
        "name": "Oxidized Silver Anklet",
        "description": "Traditional oxidized silver anklet with ethnic bells. A classic ethnic accessory for festive occasions.",
        "short_description": "Oxidized silver anklet",
        "price": 449.0,
        "original_price": 649.0,
        "discount": 30.0,
        "stock": 18,
        "rating": 4.5,
        "review_count": 70,
        "images": ["https://ik.imagekit.io/lrpk6giraj/_%20jewellery,%20jewelry%20store,%20accessories_.jpg"],
        "category": "Bracelet",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "10 inch",
        "gender": ["Women"],
        "occasions": ["Daily Wear", "Festive", "Casual"],
        "style_tags": ["Traditional", "Ethnic", "Classic"],
        "tags": ["Anklet", "Silver", "Oxidized"],
        "wear_type": "Ankle",
        "embedding_text": "Traditional oxidized silver anklet ethnic bells classic accessory for daily wear festive casual.",
        "related_products": ["prd_ox_033", "prd_ox_036"],
        "complete_look": ["prd_ox_017"],
        "featured": True,
        "is_new": False,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_044",
        "slug": "oxidized-hair-pin-set",
        "name": "Oxidized Silver Hair Pin Set",
        "description": "Elegant set of oxidized silver hair pins with ethnic design. Perfect bridal accessory.",
        "short_description": "Oxidized silver hair pin set",
        "price": 399.0,
        "original_price": 599.0,
        "discount": 33.0,
        "stock": 20,
        "rating": 4.4,
        "review_count": 45,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Welcome%20To%20My%20Shop%20MS%20Art%20Fashion%20Jewelry_.jpg"],
        "category": "Pendant",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "5 cm",
        "gender": ["Women"],
        "occasions": ["Wedding", "Festive", "Bridal"],
        "style_tags": ["Bridal", "Ethnic", "Traditional"],
        "tags": ["Hair Pin", "Silver", "Oxidized", "Bridal"],
        "wear_type": "Hair",
        "embedding_text": "Elegant oxidized silver hair pin set ethnic design perfect bridal accessory for wedding festive.",
        "related_products": ["prd_ox_040", "prd_ox_041"],
        "complete_look": ["prd_ox_040"],
        "featured": False,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_045",
        "slug": "oxidized-gifting-set",
        "name": "Oxidized Jewelry Gifting Set",
        "description": "Best oxidized jewelry gifting set for personal use and gifting. Combine for complete ethnic look.",
        "short_description": "Oxidized jewelry gifting set",
        "price": 999.0,
        "original_price": 1499.0,
        "discount": 33.0,
        "stock": 12,
        "rating": 4.7,
        "review_count": 75,
        "images": ["https://ik.imagekit.io/lrpk6giraj/-Best%20for%20Gifting%20and%20for%20personal%20Use,%20combine%20it_.jpg"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "18 inch",
        "gender": ["Women"],
        "occasions": ["Festive", "Wedding", "Gifting"],
        "style_tags": ["Traditional", "Ethnic", "Gift"],
        "tags": ["Set", "Gift", "Oxidized"],
        "wear_type": "Neck",
        "embedding_text": "Oxidized jewelry gifting set personal use ethnic traditional complete look for festive wedding gifting.",
        "related_products": ["prd_ox_038", "prd_ox_039"],
        "complete_look": ["prd_ox_003"],
        "featured": True,
        "is_new": True,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_046",
        "slug": "oxidized-meenakari-necklace",
        "name": "Oxidized Meenakari Necklace",
        "description": "Colorful oxidized meenakari necklace with traditional Indian enamel work. Vibrant ethnic jewelry.",
        "short_description": "Oxidized meenakari necklace",
        "price": 1099.0,
        "original_price": 1599.0,
        "discount": 31.0,
        "stock": 10,
        "rating": 4.8,
        "review_count": 60,
        "images": ["https://ik.imagekit.io/lrpk6giraj/124834220919344426.jpg"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver", "Meenakari"],
        "gemstones": [],
        "dimensions": "18 inch",
        "gender": ["Women"],
        "occasions": ["Festive", "Wedding", "Party"],
        "style_tags": ["Meenakari", "Colorful", "Traditional", "Ethnic"],
        "tags": ["Necklace", "Meenakari", "Oxidized", "Colorful"],
        "wear_type": "Neck",
        "embedding_text": "Colorful oxidized meenakari necklace traditional Indian enamel work vibrant ethnic jewelry for festive wedding party.",
        "related_products": ["prd_ox_010", "prd_ox_012"],
        "complete_look": ["prd_ox_002"],
        "featured": True,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_047",
        "slug": "oxidized-temple-jewelry-earrings",
        "name": "Oxidized Temple Jewelry Earrings",
        "description": "Sacred oxidized temple jewelry earrings with goddess motifs. Traditional South Indian ethnic style.",
        "short_description": "Oxidized temple jewelry earrings",
        "price": 749.0,
        "original_price": 1099.0,
        "discount": 31.0,
        "stock": 12,
        "rating": 4.8,
        "review_count": 85,
        "images": ["https://ik.imagekit.io/lrpk6giraj/253538654020224941.jpg"],
        "category": "Earrings",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "5 cm",
        "gender": ["Women"],
        "occasions": ["Religious", "Wedding", "Festive"],
        "style_tags": ["Temple", "Traditional", "Sacred", "Ethnic"],
        "tags": ["Earrings", "Temple", "Oxidized"],
        "wear_type": "Ear",
        "embedding_text": "Sacred oxidized temple jewelry earrings goddess motifs traditional South Indian ethnic style for religious wedding festive.",
        "related_products": ["prd_ox_002", "prd_ox_007"],
        "complete_look": ["prd_ox_046"],
        "featured": True,
        "is_new": False,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_048",
        "slug": "oxidized-german-silver-necklace",
        "name": "Oxidized German Silver Necklace",
        "description": "Premium oxidized German silver necklace with intricate ethnic pattern. High quality ethnic jewelry.",
        "short_description": "Oxidized German silver necklace",
        "price": 949.0,
        "original_price": 1399.0,
        "discount": 32.0,
        "stock": 10,
        "rating": 4.7,
        "review_count": 70,
        "images": ["https://ik.imagekit.io/lrpk6giraj/23995810510996966.jpg"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized German Silver"],
        "gemstones": [],
        "dimensions": "20 inch",
        "gender": ["Women"],
        "occasions": ["Festive", "Wedding", "Formal"],
        "style_tags": ["Premium", "Traditional", "Ethnic"],
        "tags": ["Necklace", "German Silver", "Oxidized"],
        "wear_type": "Neck",
        "embedding_text": "Premium oxidized German silver necklace intricate ethnic pattern high quality jewelry for festive wedding formal.",
        "related_products": ["prd_ox_010", "prd_ox_016"],
        "complete_look": ["prd_ox_047"],
        "featured": False,
        "is_new": True,
        "is_bestseller": False,
    },
    {
        "id": "prd_ox_049",
        "slug": "oxidized-peacock-necklace-set",
        "name": "Oxidized Peacock Necklace Set",
        "description": "Majestic oxidized peacock necklace set with matching earrings. Royal ethnic jewelry for special occasions.",
        "short_description": "Oxidized peacock necklace set",
        "price": 1399.0,
        "original_price": 1999.0,
        "discount": 30.0,
        "stock": 8,
        "rating": 4.9,
        "review_count": 95,
        "images": ["https://ik.imagekit.io/lrpk6giraj/Make%20a%20statement%20with%20our%20stunning%20anti-tarnished_.jpg"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver"],
        "gemstones": [],
        "dimensions": "18 inch",
        "gender": ["Women"],
        "occasions": ["Wedding", "Festive", "Party"],
        "style_tags": ["Peacock", "Royal", "Ethnic", "Statement"],
        "tags": ["Necklace", "Peacock", "Oxidized", "Set"],
        "wear_type": "Neck",
        "embedding_text": "Majestic oxidized peacock necklace set matching earrings royal ethnic jewelry for wedding festive party.",
        "related_products": ["prd_ox_040", "prd_ox_042"],
        "complete_look": ["prd_ox_006"],
        "featured": True,
        "is_new": True,
        "is_bestseller": True,
    },
    {
        "id": "prd_ox_050",
        "slug": "oxidized-kundan-necklace",
        "name": "Oxidized Kundan Style Necklace",
        "description": "Traditional oxidized kundan style necklace with ethnic design. A classic piece for bridal trousseau.",
        "short_description": "Oxidized kundan necklace",
        "price": 1299.0,
        "original_price": 1899.0,
        "discount": 31.0,
        "stock": 8,
        "rating": 4.8,
        "review_count": 85,
        "images": ["https://ik.imagekit.io/lrpk6giraj/910571619579968395.jpg"],
        "category": "Necklace",
        "collection": "Oxidized Collection",
        "materials": ["Oxidized Silver", "Kundan"],
        "gemstones": [],
        "dimensions": "18 inch",
        "gender": ["Women"],
        "occasions": ["Wedding", "Festive", "Engagement"],
        "style_tags": ["Kundan", "Bridal", "Traditional", "Royal"],
        "tags": ["Necklace", "Kundan", "Oxidized", "Bridal"],
        "wear_type": "Neck",
        "embedding_text": "Traditional oxidized kundan style necklace ethnic bridal trousseau royal classic for wedding festive engagement.",
        "related_products": ["prd_ox_040", "prd_ox_049"],
        "complete_look": ["prd_ox_009"],
        "featured": True,
        "is_new": False,
        "is_bestseller": True,
    },
]
 
 
def insert_products():
    inserted = 0
    skipped = 0
    pinecone_vectors = []
 
    for p in products:
        # Duplicate check
        existing = session.query(Product).filter_by(id=p["id"]).first()
        if existing:
            print(f"⏭ Skipped (already exists): {p['name']}")
            skipped += 1
            continue
 
        # PostgreSQL insert
        product = Product(
            id=p["id"],
            slug=p["slug"],
            name=p["name"],
            description=p["description"],
            short_description=p["short_description"],
            price=p["price"],
            original_price=p["original_price"],
            discount=p["discount"],
            stock=p["stock"],
            rating=p["rating"],
            review_count=p["review_count"],
            images=p["images"],
            category=p["category"],
            collection=p["collection"],
            materials=p["materials"],
            gemstones=p["gemstones"],
            dimensions=p["dimensions"],
            gender=p["gender"],
            occasions=p["occasions"],
            style_tags=p["style_tags"],
            tags=p["tags"],
            wear_type=p["wear_type"],
            embedding_text=p["embedding_text"],
            related_products=p["related_products"],
            complete_look=p["complete_look"],
            featured=p["featured"],
            is_new=p["is_new"],
            is_bestseller=p["is_bestseller"],
        )
        session.add(product)
 
        # Pinecone vector prepare
        pinecone_vectors.append({
            "id": p["id"],
            "values": [0.1] * 1024,
            "metadata": {
                "category": p["category"],
                "materials": p["materials"],
                "occasions": p["occasions"],
                "styleTags": p["style_tags"],
                "wearType": p["wear_type"],
                "price": p["price"],
                "collection": p["collection"],
            }
        })
 
        inserted += 1
        print(f"✅ Added: {p['name']}")
 
    # PostgreSQL commit
    session.commit()
    print(f"\n✅ PostgreSQL mein {inserted} products insert hue!")
 
    # Pinecone batch insert
    if pinecone_vectors:
        index.upsert(vectors=pinecone_vectors)
        print(f"✅ Pinecone mein {len(pinecone_vectors)} products insert hue!")
 
    print(f"\n🎉 Done! Inserted: {inserted} | Skipped: {skipped}")
 
 
if __name__ == "__main__":
    insert_products()
